import type { LexiconEntry } from "@/lib/types";

/**
 * Curated French lexicon — the A1 seed.
 *
 * Same contract as the Dutch one: `article` carries le/la here where it carries
 * de/het there, so the validator and the dictionary UI need no per-language
 * special-casing. Elided forms (j', d', l', m') are listed under `forms`
 * because they are what actually appears in the text.
 */
export const lexicon: LexiconEntry[] = [
  // ── Function words ────────────────────────────────────────────────────────
  { lemma: "le", pos: "det", en: "the (masculine)", forms: ["l'", "l'heure"], source: "curated" },
  { lemma: "la", pos: "det", en: "the (feminine)", source: "curated" },
  { lemma: "les", pos: "det", en: "the (plural)", source: "curated" },
  { lemma: "un", pos: "det", en: "a / one (masculine)", source: "curated" },
  { lemma: "une", pos: "det", en: "a (feminine)", source: "curated" },
  { lemma: "du", pos: "det", en: "of the / some (masculine)", source: "curated" },
  { lemma: "des", pos: "det", en: "of the / some (plural)", source: "curated" },
  { lemma: "de", pos: "prep", en: "of / from", forms: ["d'", "d'angleterre", "d'ouganda", "d'où"], source: "curated" },
  { lemma: "à", pos: "prep", en: "to / at / in", source: "curated" },
  { lemma: "au", pos: "prep", en: "to the / at the", source: "curated" },
  { lemma: "sous", pos: "prep", en: "under", source: "curated" },
  { lemma: "depuis", pos: "prep", en: "since / for", source: "curated" },
  { lemma: "je", pos: "pron", en: "I", forms: ["j'", "j'habite"], source: "curated" },
  { lemma: "tu", pos: "pron", en: "you (informal)", forms: ["t'", "t'appelles"], source: "curated" },
  { lemma: "vous", pos: "pron", en: "you (formal or plural)", source: "curated" },
  { lemma: "nous", pos: "pron", en: "we", source: "curated" },
  { lemma: "toi", pos: "pron", en: "you (stressed)", source: "curated" },
  { lemma: "ça", pos: "pron", en: "it / that", source: "curated" },
  { lemma: "ici", pos: "adv", en: "here", source: "curated" },
  { lemma: "et", pos: "conj", en: "and", source: "curated" },
  { lemma: "mais", pos: "conj", en: "but", source: "curated" },
  { lemma: "ou", pos: "conj", en: "or", forms: ["où"], source: "curated" },
  { lemma: "ne", pos: "adv", en: "not (first half of ne…pas)", source: "curated" },
  { lemma: "pas", pos: "adv", en: "not (second half of ne…pas)", source: "curated" },
  { lemma: "aussi", pos: "adv", en: "also", source: "curated" },
  { lemma: "bien", pos: "adv", en: "well", source: "curated" },
  { lemma: "très", pos: "adv", en: "very", source: "curated" },
  { lemma: "beaucoup", pos: "adv", en: "a lot", source: "curated" },
  { lemma: "peu", pos: "adv", en: "little", source: "curated" },
  { lemma: "tout", pos: "pron", en: "everything / all", source: "curated" },
  { lemma: "comment", pos: "adv", en: "how", source: "curated" },
  { lemma: "demain", pos: "adv", en: "tomorrow", source: "curated" },
  { lemma: "bientôt", pos: "adv", en: "soon", source: "curated" },

  // ── Greetings ─────────────────────────────────────────────────────────────
  { lemma: "bonjour", pos: "interj", en: "hello / good morning", source: "curated" },
  { lemma: "bonsoir", pos: "interj", en: "good evening", source: "curated" },
  { lemma: "salut", pos: "interj", en: "hi / bye (informal)", source: "curated" },
  { lemma: "merci", pos: "interj", en: "thank you", source: "curated" },
  { lemma: "revoir", pos: "noun", en: "seeing again (bound form, only in \"au revoir\")", flags: ["bound"], source: "curated" },
  { lemma: "enchanté", pos: "adj", en: "pleased to meet you", forms: ["enchantée"], source: "curated" },
  { lemma: "désolé", pos: "adj", en: "sorry", forms: ["désolée"], source: "curated" },

  // ── Verbs ─────────────────────────────────────────────────────────────────
  {
    lemma: "être",
    pos: "verb",
    en: "to be",
    participle: "été",
    flags: ["irregular"],
    forms: ["suis", "es", "est", "sommes", "êtes", "sont"],
    source: "curated",
  },
  {
    lemma: "avoir",
    pos: "verb",
    en: "to have",
    participle: "eu",
    flags: ["irregular"],
    forms: ["ai", "as", "a", "avons", "avez", "ont"],
    source: "curated",
  },
  {
    lemma: "aller",
    pos: "verb",
    en: "to go",
    participle: "allé",
    flags: ["irregular"],
    forms: ["vais", "vas", "va", "allons", "allez", "vont"],
    source: "curated",
  },
  {
    lemma: "s'appeler",
    pos: "verb",
    en: "to be called",
    participle: "appelé",
    flags: ["reflexive"],
    forms: ["appelle", "appelles", "appelez", "m'appelle", "t'appelles"],
    source: "curated",
  },
  {
    lemma: "venir",
    pos: "verb",
    en: "to come",
    participle: "venu",
    flags: ["irregular"],
    forms: ["viens", "vient", "venons", "venez", "viennent"],
    source: "curated",
  },
  {
    lemma: "habiter",
    pos: "verb",
    en: "to live / reside",
    participle: "habité",
    forms: ["habite", "habites", "habitez"],
    source: "curated",
  },
  {
    lemma: "parler",
    pos: "verb",
    en: "to speak",
    participle: "parlé",
    forms: ["parle", "parles", "parlez", "parlons"],
    source: "curated",
  },
  {
    lemma: "comprendre",
    pos: "verb",
    en: "to understand",
    participle: "compris",
    flags: ["irregular"],
    forms: ["comprends", "comprend", "comprenez"],
    source: "curated",
  },
  {
    lemma: "devoir",
    pos: "verb",
    en: "must / to have to",
    participle: "dû",
    flags: ["irregular", "modal"],
    forms: ["dois", "doit", "devez"],
    source: "curated",
  },
  { lemma: "partir", pos: "verb", en: "to leave", participle: "parti", flags: ["irregular"], forms: ["pars", "part"], source: "curated" },
  { lemma: "voir", pos: "verb", en: "to see", participle: "vu", flags: ["irregular"], forms: ["vois", "voit", "voyez"], source: "curated" },
  { lemma: "regarder", pos: "verb", en: "to watch / look at", participle: "regardé", forms: ["regarde", "regardent"], source: "curated" },

  // ── Nouns ─────────────────────────────────────────────────────────────────
  { lemma: "an", pos: "noun", article: "le", plural: "ans", en: "year", source: "curated" },
  { lemma: "heure", pos: "noun", article: "la", plural: "heures", en: "hour", source: "curated" },
  { lemma: "ami", pos: "noun", article: "le", plural: "amis", en: "friend", source: "curated" },
  { lemma: "rue", pos: "noun", article: "la", plural: "rues", en: "street", source: "curated" },
  { lemma: "rat", pos: "noun", article: "le", plural: "rats", en: "rat", source: "curated" },
  { lemma: "chat", pos: "noun", article: "le", plural: "chats", en: "cat", source: "curated" },
  { lemma: "vin", pos: "noun", article: "le", plural: "vins", en: "wine", source: "curated" },
  { lemma: "accueil", pos: "noun", article: "le", en: "welcome / reception", source: "curated" },
  { lemma: "français", pos: "noun", article: "le", en: "French", source: "curated" },

  // ── Adjectives and numbers ────────────────────────────────────────────────
  { lemma: "bon", pos: "adj", en: "good", forms: ["bonne"], source: "curated" },
  { lemma: "petit", pos: "adj", en: "small", forms: ["petite"], source: "curated" },
  { lemma: "grand", pos: "adj", en: "big", forms: ["grande"], source: "curated" },
  { lemma: "blanc", pos: "adj", en: "white", forms: ["blanche"], source: "curated" },
  { lemma: "gris", pos: "adj", en: "grey", forms: ["grise"], source: "curated" },
  { lemma: "rouge", pos: "adj", en: "red", source: "curated" },
  { lemma: "deux", pos: "num", en: "two", source: "curated" },
  { lemma: "trois", pos: "num", en: "three", source: "curated" },

  // ── Proper nouns ──────────────────────────────────────────────────────────
  { lemma: "josh", pos: "name", en: "Josh", source: "curated" },
  { lemma: "claire", pos: "name", en: "Claire", source: "curated" },
  { lemma: "paris", pos: "name", en: "Paris", source: "curated" },
  { lemma: "lyon", pos: "name", en: "Lyon", source: "curated" },
  { lemma: "angleterre", pos: "name", en: "England", source: "curated" },
  { lemma: "ouganda", pos: "name", en: "Uganda", source: "curated" },
  { lemma: "canada", pos: "name", en: "Canada", source: "curated" },
  { lemma: "états", pos: "name", en: "States (in États-Unis)", forms: ["états-unis", "unis"], source: "curated" },
];
