import type { Lesson } from "@/lib/types";

export const lessons: Lesson[] = [
  // ── Unit 1 ────────────────────────────────────────────────────────────────
  {
    id: "groeten",
    unit: "contact",
    title: "Hallo en tot ziens",
    titleEn: "Hello and goodbye",
    canDo: "Open and close a conversation without switching to English.",
    level: "A1",
    phrases: [
      {
        id: "hoe-gaat-het",
        target: "Hoi, hoe gaat het?",
        en: "Hi, how's it going?",
        gloss: [
          { target: "Hoi", en: "hi" },
          { target: "hoe", en: "how" },
          { target: "gaat", en: "goes" },
          { target: "het", en: "it" },
        ],
        register: "informal",
        say: "hoy, hoo GHAAT ut — the g is the scraped sound at the back of the throat",
        note: "Say it as one blur: hoegaatut. Dutch people do not pause between these words.",
      },
      {
        id: "goed-dank-je",
        target: "Het gaat goed, dank je. En met jou?",
        en: "I'm doing well, thanks. And you?",
        gloss: [
          { target: "Het gaat", en: "it goes" },
          { target: "goed", en: "well" },
          { target: "dank je", en: "thank you" },
          { target: "en met jou", en: "and with you" },
        ],
        register: "informal",
        say: "ut ghaat GHOOT, dank yuh. en met YAW",
        note: "Bouncing the question back with 'En met jou?' is what makes you sound like a person and not a phrasebook.",
      },
      {
        id: "goedemorgen",
        target: "Goedemorgen",
        en: "Good morning",
        gloss: [
          { target: "goede", en: "good" },
          { target: "morgen", en: "morning" },
        ],
        register: "neutral",
        say: "ghoo-duh-MOR-ghun",
        pattern: {
          template: "Goede___",
          templateEn: "Good ___",
          slots: [
            { target: "Goedemorgen", en: "Good morning (until ~12)" },
            { target: "Goedemiddag", en: "Good afternoon (12–18)" },
            { target: "Goedenavond", en: "Good evening (after ~18)" },
          ],
        },
      },
      {
        id: "aangenaam",
        target: "Aangenaam",
        en: "Pleased to meet you",
        gloss: [{ target: "aangenaam", en: "pleasant" }],
        register: "formal",
        say: "AAN-ghuh-naam — long open aa, like the a in 'father' held longer",
        note: "One word, does the whole job. Slightly formal; with friends a simple 'Hoi' is plenty.",
      },
      {
        id: "tot-ziens",
        target: "Tot ziens",
        en: "Goodbye",
        gloss: [
          { target: "tot", en: "until" },
          { target: "ziens", en: "seeing" },
        ],
        register: "neutral",
        say: "tot SEENS",
        pattern: {
          template: "Tot ___",
          templateEn: "See you ___",
          slots: [
            { target: "Tot ziens", en: "Goodbye (neutral, safe anywhere)" },
            { target: "Tot morgen", en: "See you tomorrow" },
            { target: "Tot straks", en: "See you later today" },
            { target: "Tot volgende week", en: "See you next week" },
          ],
        },
      },
      {
        id: "hoe-is-het",
        target: "Hoe is het met je?",
        en: "How are you doing?",
        gloss: [
          { target: "hoe is het", en: "how is it" },
          { target: "met je", en: "with you" },
        ],
        register: "informal",
        say: "hoo is ut met yuh",
        note: "A slightly warmer alternative to 'hoe gaat het'. Use it with people you already know.",
      },
      {
        id: "niet-zo-goed",
        target: "Niet zo goed, eerlijk gezegd.",
        en: "Not so good, honestly.",
        gloss: [
          { target: "niet zo goed", en: "not so good" },
          { target: "eerlijk gezegd", en: "honestly said" },
        ],
        say: "neet zo GHOOT, AYR-luk khuh-ZEKHT",
        note: "Dutch people answer this question truthfully. 'Fine' when you are not fine reads as evasive rather than polite.",
      },
      {
        id: "lang-niet-gezien",
        target: "Lang niet gezien!",
        en: "Long time no see!",
        gloss: [
          { target: "lang", en: "long" },
          { target: "niet", en: "not" },
          { target: "gezien", en: "seen" },
        ],
        say: "lang neet khuh-ZEEN",
      },
      {
        id: "fijne-dag",
        target: "Fijne dag nog!",
        en: "Have a nice day!",
        gloss: [
          { target: "fijne", en: "nice" },
          { target: "dag", en: "day" },
          { target: "nog", en: "still / further" },
        ],
        say: "FAY-nuh dakh nokh",
        note: "The standard sign-off in shops. 'Nog' adds 'for the rest of it' and has no clean English equivalent.",
      },
      {
        id: "tot-later",
        target: "Tot later!",
        en: "See you later!",
        gloss: [
          { target: "tot", en: "until" },
          { target: "later", en: "later" },
        ],
        say: "tot LAA-ter",
      },
      {
        id: "doei",
        target: "Doei!",
        en: "Bye!",
        gloss: [{ target: "doei", en: "bye" }],
        register: "informal",
        say: "DOO-ee, sliding the two vowels together",
        note: "The everyday goodbye. You will hear 'doei doei' — doubling it is friendly, not childish.",
      },
    ],
    dialogue: [
      { speaker: "them", target: "Hoi! Hoe gaat het?", en: "Hi! How's it going?" },
      {
        speaker: "you",
        target: "Het gaat goed, dank je. En met jou?",
        en: "I'm doing well, thanks. And you?",
        cue: "Say you're doing well, thank them, and ask back.",
      },
      { speaker: "them", target: "Ook goed! Ik moet gaan.", en: "Also good! I have to go." },
      {
        speaker: "you",
        target: "Tot morgen!",
        en: "See you tomorrow!",
        cue: "Say goodbye — you'll see them tomorrow.",
      },
    ],
    roleplay:
      "You bump into the learner in the hallway of your shared apartment building in Utrecht. Greet them, ask how they are, chat for two or three exchanges about something small (the weather, the stairs, the neighbour's dog), then say you have to go.",
  },
  {
    id: "voorstellen",
    unit: "contact",
    title: "Wie ben jij?",
    titleEn: "Who are you?",
    canDo: "Introduce yourself and say where you're from and what you do.",
    level: "A1",
    phrases: [
      {
        id: "ik-heet",
        target: "Ik heet Josh.",
        en: "My name is Josh.",
        gloss: [
          { target: "ik", en: "I" },
          { target: "heet", en: "am called" },
          { target: "Josh", en: "Josh" },
        ],
        say: "ik HAYT",
        note: "Literally 'I am called'. 'Ik ben Josh' works too and is a touch more casual.",
        pattern: {
          template: "Ik heet ___.",
          templateEn: "My name is ___.",
          slots: [
            { target: "Ik heet Josh.", en: "My name is Josh." },
            { target: "Ik ben Josh.", en: "I'm Josh." },
            { target: "Mijn naam is Josh.", en: "My name is Josh. (formal)" },
          ],
        },
      },
      {
        id: "hoe-heet-jij",
        target: "Hoe heet jij?",
        en: "What's your name?",
        gloss: [
          { target: "hoe", en: "how" },
          { target: "heet", en: "are called" },
          { target: "jij", en: "you" },
        ],
        register: "informal",
        say: "hoo HAYT yay",
        note: "Formal version: 'Hoe heet u?' Use u with older strangers and in shops if you want to be safe.",
      },
      {
        id: "ik-kom-uit",
        target: "Ik kom uit Engeland.",
        en: "I'm from England.",
        gloss: [
          { target: "ik", en: "I" },
          { target: "kom", en: "come" },
          { target: "uit", en: "from" },
          { target: "Engeland", en: "England" },
        ],
        say: "ik kom OWT — 'uit' is the ui sound, mouth rounded then spread",
        pattern: {
          template: "Ik kom uit ___.",
          templateEn: "I'm from ___.",
          slots: [
            { target: "Ik kom uit Engeland.", en: "I'm from England." },
            { target: "Ik kom uit Amerika.", en: "I'm from America." },
            { target: "Ik kom uit Oeganda.", en: "I'm from Uganda." },
            { target: "Ik kom uit Zuid-Afrika.", en: "I'm from South Africa." },
          ],
        },
      },
      {
        id: "ik-woon-in",
        target: "Ik woon in Amsterdam.",
        en: "I live in Amsterdam.",
        gloss: [
          { target: "ik", en: "I" },
          { target: "woon", en: "live" },
          { target: "in", en: "in" },
          { target: "Amsterdam", en: "Amsterdam" },
        ],
        say: "ik VOAN in — Dutch w is between English v and w, lips lightly touching teeth",
        pattern: {
          template: "Ik woon in ___.",
          templateEn: "I live in ___.",
          slots: [
            { target: "Ik woon in Amsterdam.", en: "I live in Amsterdam." },
            { target: "Ik woon in Rotterdam.", en: "I live in Rotterdam." },
            { target: "Ik woon hier al twee jaar.", en: "I've lived here for two years." },
          ],
        },
      },
      {
        id: "beetje-nederlands",
        target: "Ik spreek een beetje Nederlands.",
        en: "I speak a little Dutch.",
        gloss: [
          { target: "ik spreek", en: "I speak" },
          { target: "een beetje", en: "a little" },
          { target: "Nederlands", en: "Dutch" },
        ],
        say: "ik SPRAYK un BAY-chuh NAY-der-lants",
        note: "Your single most useful sentence. It buys patience and stops people switching to English.",
      },
      {
        id: "wat-doe-je",
        target: "Wat doe je voor werk?",
        en: "What do you do for work?",
        gloss: [
          { target: "wat", en: "what" },
          { target: "doe", en: "do" },
          { target: "je", en: "you" },
          { target: "voor werk", en: "for work" },
        ],
        register: "informal",
        say: "vat DOO yuh voor VERK",
      },
    ],
    dialogue: [
      { speaker: "them", target: "Hoi! Ik ben Sanne. Hoe heet jij?", en: "Hi! I'm Sanne. What's your name?" },
      {
        speaker: "you",
        target: "Ik heet Josh. Aangenaam.",
        en: "My name is Josh. Pleased to meet you.",
        cue: "Give your name and say it's nice to meet them.",
      },
      { speaker: "them", target: "Aangenaam! Waar kom je vandaan?", en: "Nice to meet you! Where are you from?" },
      {
        speaker: "you",
        target: "Ik kom uit Engeland, maar ik woon in Amsterdam.",
        en: "I'm from England, but I live in Amsterdam.",
        cue: "Say where you're from, then where you live now. Join them with 'maar' (but).",
      },
      { speaker: "them", target: "Wat leuk! Spreek je Nederlands?", en: "How nice! Do you speak Dutch?" },
      {
        speaker: "you",
        target: "Ik spreek een beetje Nederlands.",
        en: "I speak a little Dutch.",
        cue: "Tell them you speak a bit of Dutch.",
      },
    ],
    roleplay:
      "You are a friendly Dutch person at a housewarming party. You've just been introduced to the learner. Find out their name, where they're from, where they live now, and what they do. Share the same about yourself. Keep your Dutch simple and warm.",
  },
  {
    id: "vastlopen",
    unit: "contact",
    title: "Als je vastloopt",
    titleEn: "When you get stuck",
    canDo: "Stay in the conversation when you didn't catch something.",
    level: "A1",
    phrases: [
      {
        id: "sorry-begrijp-niet",
        target: "Sorry, ik begrijp het niet.",
        en: "Sorry, I don't understand.",
        gloss: [
          { target: "sorry", en: "sorry" },
          { target: "ik begrijp", en: "I understand" },
          { target: "het", en: "it" },
          { target: "niet", en: "not" },
        ],
        say: "sorry, ik buh-GHRAYP ut neet",
        note: "Dutch puts 'niet' at the end. That ordering — negation last — will come up constantly.",
      },
      {
        id: "langzamer",
        target: "Kun je wat langzamer praten?",
        en: "Could you speak a bit more slowly?",
        gloss: [
          { target: "kun je", en: "can you" },
          { target: "wat", en: "a bit" },
          { target: "langzamer", en: "slower" },
          { target: "praten", en: "to speak" },
        ],
        register: "informal",
        say: "kun yuh vat LANG-zaa-mer PRAA-tun",
        note: "The verb goes to the very end. 'Kun je ... praten?' wraps around everything in between.",
      },
      {
        id: "herhalen",
        target: "Kunt u dat herhalen, alstublieft?",
        en: "Could you repeat that, please?",
        gloss: [
          { target: "kunt u", en: "can you (formal)" },
          { target: "dat", en: "that" },
          { target: "herhalen", en: "to repeat" },
          { target: "alstublieft", en: "please" },
        ],
        register: "formal",
        say: "kunt oo dat her-HAA-lun, als-too-BLEEFT",
      },
      {
        id: "hoe-zeg-je",
        target: "Hoe zeg je dat in het Nederlands?",
        en: "How do you say that in Dutch?",
        gloss: [
          { target: "hoe", en: "how" },
          { target: "zeg je", en: "say you" },
          { target: "dat", en: "that" },
          { target: "in het Nederlands", en: "in Dutch" },
        ],
        register: "informal",
        say: "hoo ZEGH yuh dat in ut NAY-der-lants",
        note: "This is how you get free vocabulary out of every conversation you have.",
      },
      {
        id: "wat-betekent",
        target: "Wat betekent dat?",
        en: "What does that mean?",
        gloss: [
          { target: "wat", en: "what" },
          { target: "betekent", en: "means" },
          { target: "dat", en: "that" },
        ],
        say: "vat buh-TAY-kunt dat",
      },
      {
        id: "spreekt-engels",
        target: "Spreekt u Engels?",
        en: "Do you speak English?",
        gloss: [
          { target: "spreekt u", en: "speak you (formal)" },
          { target: "Engels", en: "English" },
        ],
        register: "formal",
        say: "SPRAYKT oo ENG-uls",
        note: "Your escape hatch. Try the Dutch first — reaching for this too early is how people stay beginners.",
      },
    ],
    dialogue: [
      {
        speaker: "them",
        target: "Zal ik het even voor je opschrijven of stuur ik het door?",
        en: "Shall I write it down for you or shall I forward it?",
      },
      {
        speaker: "you",
        target: "Sorry, ik begrijp het niet. Kun je wat langzamer praten?",
        en: "Sorry, I don't understand. Could you speak a bit more slowly?",
        cue: "Say you don't understand, and ask them to slow down.",
      },
      { speaker: "them", target: "Natuurlijk. Zal ... ik ... het ... opschrijven?", en: "Of course. Shall I write it down?" },
      {
        speaker: "you",
        target: "Wat betekent 'opschrijven'?",
        en: "What does 'opschrijven' mean?",
        cue: "Ask what the word 'opschrijven' means.",
      },
      { speaker: "them", target: "Het betekent 'to write down'.", en: "It means 'to write down'." },
      { speaker: "you", target: "Ah, dank je wel!", en: "Ah, thank you!", cue: "Thank them." },
    ],
    roleplay:
      "You are a Dutch colleague explaining something mildly complicated to the learner — how the office coffee machine works, or where to hand in a form. Speak naturally and use one or two words slightly above their level, so they have to use the repair phrases. Be patient and rephrase happily when they ask.",
  },

  // ── Unit 2 ────────────────────────────────────────────────────────────────
  {
    id: "cafe",
    unit: "eten",
    title: "In het café",
    titleEn: "At the café",
    canDo: "Order, ask the price, and pay — start to finish, in Dutch.",
    level: "A1",
    phrases: [
      {
        id: "mag-ik",
        target: "Mag ik een koffie, alstublieft?",
        en: "Could I have a coffee, please?",
        gloss: [
          { target: "mag ik", en: "may I" },
          { target: "een koffie", en: "a coffee" },
          { target: "alstublieft", en: "please" },
        ],
        register: "formal",
        say: "makh ik un KOF-ee, als-too-BLEEFT",
        note: "The workhorse ordering phrase. Swap the noun and you can order anything in the country.",
        pattern: {
          template: "Mag ik ___, alstublieft?",
          templateEn: "Could I have ___, please?",
          slots: [
            { target: "Mag ik een koffie, alstublieft?", en: "a coffee" },
            { target: "Mag ik een biertje, alstublieft?", en: "a beer" },
            { target: "Mag ik een glas water, alstublieft?", en: "a glass of water" },
            { target: "Mag ik de kaart, alstublieft?", en: "the menu" },
          ],
        },
      },
      {
        id: "ik-wil-graag",
        target: "Ik wil graag een broodje kaas.",
        en: "I'd like a cheese sandwich.",
        gloss: [
          { target: "ik wil", en: "I want" },
          { target: "graag", en: "gladly" },
          { target: "een broodje kaas", en: "a cheese roll" },
        ],
        say: "ik vil GHRAAKH un BROAD-yuh KAAS",
        note: "'Graag' is the politeness engine of Dutch. 'Ik wil' alone is blunt; 'ik wil graag' is perfectly polite.",
      },
      {
        id: "voor-hier",
        target: "Voor hier of om mee te nemen?",
        en: "For here or to take away?",
        gloss: [
          { target: "voor hier", en: "for here" },
          { target: "of", en: "or" },
          { target: "om mee te nemen", en: "to take with" },
        ],
        say: "voor HEER of om may tuh NAY-mun",
        note: "You won't say this — you'll hear it. Learn it as a sound so it doesn't ambush you.",
      },
      {
        id: "om-mee-te-nemen",
        target: "Om mee te nemen, graag.",
        en: "To take away, please.",
        gloss: [
          { target: "om mee te nemen", en: "to take with" },
          { target: "graag", en: "gladly" },
        ],
        say: "om may tuh NAY-mun, GHRAAKH",
      },
      {
        id: "wat-kost-dat",
        target: "Wat kost dat?",
        en: "How much is that?",
        gloss: [
          { target: "wat", en: "what" },
          { target: "kost", en: "costs" },
          { target: "dat", en: "that" },
        ],
        say: "vat KOST dat",
      },
      {
        id: "kan-ik-pinnen",
        target: "Kan ik pinnen?",
        en: "Can I pay by card?",
        gloss: [
          { target: "kan ik", en: "can I" },
          { target: "pinnen", en: "to pay by debit card" },
        ],
        say: "kan ik PIN-un",
        note: "'Pinnen' is card payment. Very Dutch, no English equivalent — and many places are card-only.",
      },
      {
        id: "de-rekening",
        target: "De rekening, alstublieft.",
        en: "The bill, please.",
        gloss: [
          { target: "de rekening", en: "the bill" },
          { target: "alstublieft", en: "please" },
        ],
        say: "duh RAY-kuh-ning, als-too-BLEEFT",
      },
    ],
    dialogue: [
      { speaker: "them", target: "Goedemiddag! Zegt u het maar.", en: "Good afternoon! What can I get you?" },
      {
        speaker: "you",
        target: "Mag ik een koffie, alstublieft?",
        en: "Could I have a coffee, please?",
        cue: "Order a coffee, politely.",
      },
      { speaker: "them", target: "Zeker. Voor hier of om mee te nemen?", en: "Certainly. For here or to take away?" },
      {
        speaker: "you",
        target: "Voor hier, graag.",
        en: "For here, please.",
        cue: "You're staying. Say so, with 'graag'.",
      },
      { speaker: "them", target: "Dat is drie euro vijftig.", en: "That's three euros fifty." },
      {
        speaker: "you",
        target: "Kan ik pinnen?",
        en: "Can I pay by card?",
        cue: "Ask if you can pay by card.",
      },
      { speaker: "them", target: "Natuurlijk. Alstublieft!", en: "Of course. Here you go!" },
    ],
    roleplay:
      "You are a barista in a busy Amsterdam café. Greet the learner, take their order, ask for-here-or-takeaway, name a price, handle payment, and send them off. Stay in Dutch and keep it brisk and friendly, like a real café.",
  },
  {
    id: "de-weg",
    unit: "stad",
    title: "De weg vragen",
    titleEn: "Asking directions",
    canDo: "Ask where something is — and understand the answer you get back.",
    level: "A1",
    phrases: [
      {
        id: "waar-is",
        target: "Waar is het station?",
        en: "Where is the station?",
        gloss: [
          { target: "waar", en: "where" },
          { target: "is", en: "is" },
          { target: "het station", en: "the station" },
        ],
        say: "vaar is ut sta-SHON",
        pattern: {
          template: "Waar is ___?",
          templateEn: "Where is ___?",
          slots: [
            { target: "Waar is het station?", en: "the station" },
            { target: "Waar is de supermarkt?", en: "the supermarket" },
            { target: "Waar is het toilet?", en: "the toilet" },
            { target: "Waar is de dichtstbijzijnde halte?", en: "the nearest stop" },
          ],
        },
      },
      {
        id: "hoe-kom-ik",
        target: "Hoe kom ik bij het museum?",
        en: "How do I get to the museum?",
        gloss: [
          { target: "hoe", en: "how" },
          { target: "kom ik", en: "come I" },
          { target: "bij", en: "at/to" },
          { target: "het museum", en: "the museum" },
        ],
        say: "hoo kom ik bay ut mu-ZAY-um",
        note: "Question word first, then the verb, then 'ik'. Dutch flips subject and verb in questions — same as 'how do I'.",
      },
      {
        id: "is-het-ver",
        target: "Is het ver?",
        en: "Is it far?",
        gloss: [
          { target: "is het", en: "is it" },
          { target: "ver", en: "far" },
        ],
        say: "is ut VER",
      },
      {
        id: "rechtdoor",
        target: "Rechtdoor, dan links.",
        en: "Straight on, then left.",
        gloss: [
          { target: "rechtdoor", en: "straight ahead" },
          { target: "dan", en: "then" },
          { target: "links", en: "left" },
        ],
        say: "REKHT-door, dan LINKS",
        note: "Careful: 'rechts' is right, 'rechtdoor' is straight on. One letter, very different walk.",
        pattern: {
          template: "___",
          templateEn: "Direction words",
          slots: [
            { target: "rechtdoor", en: "straight ahead" },
            { target: "links", en: "left" },
            { target: "rechts", en: "right" },
            { target: "de eerste straat rechts", en: "the first street on the right" },
            { target: "om de hoek", en: "around the corner" },
          ],
        },
      },
      {
        id: "verdwaald",
        target: "Ik ben verdwaald.",
        en: "I'm lost.",
        gloss: [
          { target: "ik ben", en: "I am" },
          { target: "verdwaald", en: "lost" },
        ],
        say: "ik ben ver-DVAALT",
      },
      {
        id: "hier-vlakbij",
        target: "Het is hier vlakbij.",
        en: "It's nearby.",
        gloss: [
          { target: "het is", en: "it is" },
          { target: "hier", en: "here" },
          { target: "vlakbij", en: "close by" },
        ],
        say: "ut is heer VLAK-bay",
      },
    ],
    dialogue: [
      {
        speaker: "you",
        target: "Pardon, waar is het station?",
        en: "Excuse me, where is the station?",
        cue: "Get their attention politely, then ask where the station is.",
      },
      {
        speaker: "them",
        target: "Rechtdoor, dan de eerste straat rechts.",
        en: "Straight on, then the first street on the right.",
      },
      { speaker: "you", target: "Is het ver?", en: "Is it far?", cue: "Ask whether it's far." },
      { speaker: "them", target: "Nee hoor, het is hier vlakbij. Vijf minuten.", en: "Not at all, it's nearby. Five minutes." },
      { speaker: "you", target: "Dank u wel!", en: "Thank you!", cue: "Thank them — formally, they're a stranger." },
    ],
    roleplay:
      "You are a helpful passer-by on a street in Utrecht. The learner will stop you to ask for directions. Give clear, simple directions using rechtdoor / links / rechts and a rough walking time. If they ask follow-ups, answer patiently.",
  },
  {
    id: "winkelen",
    unit: "winkelen",
    title: "Boodschappen doen",
    titleEn: "Shopping",
    canDo: "Handle a shop: browse, ask, choose, pay.",
    level: "A1",
    phrases: [
      {
        id: "ik-kijk-rond",
        target: "Ik kijk alleen even rond.",
        en: "I'm just browsing.",
        gloss: [
          { target: "ik kijk", en: "I look" },
          { target: "alleen", en: "only" },
          { target: "even", en: "just/briefly" },
          { target: "rond", en: "around" },
        ],
        say: "ik kayk al-LAYN AY-vun RONT",
        note: "'Even' is a tiny word Dutch people sprinkle everywhere to soften a sentence. Copy the habit.",
      },
      {
        id: "ik-zoek",
        target: "Ik zoek een cadeau.",
        en: "I'm looking for a gift.",
        gloss: [
          { target: "ik zoek", en: "I seek" },
          { target: "een cadeau", en: "a gift" },
        ],
        say: "ik ZOOK un ka-DOH",
        pattern: {
          template: "Ik zoek ___.",
          templateEn: "I'm looking for ___.",
          slots: [
            { target: "Ik zoek een cadeau.", en: "a gift" },
            { target: "Ik zoek een jas.", en: "a coat" },
            { target: "Ik zoek melk.", en: "milk" },
            { target: "Ik zoek iets goedkopers.", en: "something cheaper" },
          ],
        },
      },
      {
        id: "andere-maat",
        target: "Heeft u dit in een andere maat?",
        en: "Do you have this in a different size?",
        gloss: [
          { target: "heeft u", en: "have you (formal)" },
          { target: "dit", en: "this" },
          { target: "in een andere maat", en: "in another size" },
        ],
        register: "formal",
        say: "hayft oo dit in un AN-duh-ruh MAAT",
      },
      {
        id: "mag-ik-passen",
        target: "Mag ik dit passen?",
        en: "Can I try this on?",
        gloss: [
          { target: "mag ik", en: "may I" },
          { target: "dit", en: "this" },
          { target: "passen", en: "to try on" },
        ],
        say: "makh ik dit PAS-un",
      },
      {
        id: "hoeveel-kost",
        target: "Hoeveel kost het?",
        en: "How much does it cost?",
        gloss: [
          { target: "hoeveel", en: "how much" },
          { target: "kost", en: "costs" },
          { target: "het", en: "it" },
        ],
        say: "hoo-VAYL kost ut",
      },
      {
        id: "ik-neem-het",
        target: "Ik neem het.",
        en: "I'll take it.",
        gloss: [
          { target: "ik neem", en: "I take" },
          { target: "het", en: "it" },
        ],
        say: "ik NAYM ut",
      },
      {
        id: "misschien-later",
        target: "Misschien kom ik later terug.",
        en: "Maybe I'll come back later.",
        gloss: [
          { target: "misschien", en: "maybe" },
          { target: "kom ik", en: "come I" },
          { target: "later terug", en: "later back" },
        ],
        say: "mis-SKHEEN kom ik LAA-ter tuh-RUKH",
        note: "Note the flip: after 'misschien' the verb jumps in front of 'ik'. Dutch keeps the verb in second position, always.",
      },
    ],
    dialogue: [
      { speaker: "them", target: "Goedemiddag! Kan ik u helpen?", en: "Good afternoon! Can I help you?" },
      {
        speaker: "you",
        target: "Ik kijk alleen even rond, dank u.",
        en: "I'm just browsing, thank you.",
        cue: "Say you're just browsing, and thank them.",
      },
      { speaker: "them", target: "Prima, roept u maar als u iets nodig heeft.", en: "Fine, just call if you need anything." },
      {
        speaker: "you",
        target: "Heeft u dit in een andere maat?",
        en: "Do you have this in a different size?",
        cue: "You found something. Ask for a different size.",
      },
      { speaker: "them", target: "Momentje, ik kijk even. Welke maat zoekt u?", en: "One moment, I'll check. Which size are you looking for?" },
      {
        speaker: "you",
        target: "Medium, graag. Hoeveel kost het?",
        en: "Medium, please. How much does it cost?",
        cue: "Say medium, then ask the price.",
      },
    ],
    roleplay:
      "You are a shop assistant in a clothing shop in Den Haag. Greet the learner, offer help, answer questions about sizes and prices, and take them through to paying. Keep sentences short and natural.",
  },
];
