import type { LexiconEntry } from "@/lib/types";

/**
 * Curated Dutch lexicon — the A1 core.
 *
 * Two jobs at once: it backs the in-app dictionary, and `npm run validate`
 * checks every phrase in the curriculum against it. That second job is why
 * articles and forms are filled in carefully — a wrong `de` here would be
 * copied into lessons rather than caught.
 *
 * `forms` lists inflected surface forms so the validator recognises them
 * without needing a morphological analyser.
 */
export const lexicon: LexiconEntry[] = [
  // ── Function words ────────────────────────────────────────────────────────
  { lemma: "de", pos: "det", en: "the (common gender)", source: "curated" },
  { lemma: "het", pos: "det", en: "the (neuter) / it", source: "curated" },
  { lemma: "een", pos: "det", en: "a / one", source: "curated" },
  { lemma: "ik", pos: "pron", en: "I", source: "curated" },
  { lemma: "jij", pos: "pron", en: "you (informal)", forms: ["je"], source: "curated" },
  { lemma: "u", pos: "pron", en: "you (formal)", source: "curated" },
  { lemma: "wij", pos: "pron", en: "we", forms: ["we"], source: "curated" },
  { lemma: "zij", pos: "pron", en: "she / they", forms: ["ze"], source: "curated" },
  { lemma: "jullie", pos: "pron", en: "you (plural)", source: "curated" },
  { lemma: "jou", pos: "pron", en: "you (object, informal)", source: "curated" },
  { lemma: "dat", pos: "pron", en: "that", source: "curated" },
  { lemma: "dit", pos: "pron", en: "this", source: "curated" },
  { lemma: "iets", pos: "pron", en: "something", source: "curated" },
  { lemma: "mijn", pos: "det", en: "my", source: "curated" },
  { lemma: "ons", pos: "det", en: "our (before het-words)", forms: ["onze"], source: "curated" },
  { lemma: "welke", pos: "det", en: "which", source: "curated" },
  { lemma: "andere", pos: "adj", en: "other", source: "curated" },
  { lemma: "en", pos: "conj", en: "and", source: "curated" },
  { lemma: "of", pos: "conj", en: "or", source: "curated" },
  { lemma: "maar", pos: "conj", en: "but", source: "curated" },
  { lemma: "als", pos: "conj", en: "if / when", source: "curated" },
  { lemma: "dan", pos: "adv", en: "then / than", source: "curated" },
  { lemma: "niet", pos: "adv", en: "not", source: "curated" },
  { lemma: "geen", pos: "det", en: "no / not a", source: "curated" },
  { lemma: "nee", pos: "interj", en: "no", source: "curated" },
  { lemma: "wel", pos: "adv", en: "indeed (positive counterpart of niet)", source: "curated" },
  { lemma: "ook", pos: "adv", en: "also", source: "curated" },
  { lemma: "al", pos: "adv", en: "already", source: "curated" },
  { lemma: "alleen", pos: "adv", en: "only / alone", source: "curated" },
  { lemma: "even", pos: "adv", en: "just / briefly", source: "curated" },
  { lemma: "hier", pos: "adv", en: "here", source: "curated" },
  { lemma: "waar", pos: "adv", en: "where", source: "curated" },
  { lemma: "waarom", pos: "adv", en: "why", source: "curated" },
  { lemma: "hoe", pos: "adv", en: "how", source: "curated" },
  { lemma: "wat", pos: "pron", en: "what / a bit", source: "curated" },
  { lemma: "hoeveel", pos: "adv", en: "how much", source: "curated" },
  { lemma: "misschien", pos: "adv", en: "maybe", source: "curated" },
  { lemma: "natuurlijk", pos: "adv", en: "of course", source: "curated" },
  { lemma: "zeker", pos: "adv", en: "certainly", source: "curated" },
  { lemma: "prima", pos: "adj", en: "fine", source: "curated" },
  { lemma: "graag", pos: "adv", en: "gladly (politeness marker)", source: "curated" },
  { lemma: "hoor", pos: "interj", en: "softening particle", source: "curated" },
  { lemma: "vandaan", pos: "adv", en: "from (with waar)", source: "curated" },
  { lemma: "terug", pos: "adv", en: "back", source: "curated" },
  { lemma: "rond", pos: "adv", en: "around", source: "curated" },
  { lemma: "later", pos: "adv", en: "later", source: "curated" },
  { lemma: "straks", pos: "adv", en: "later today", source: "curated" },
  { lemma: "volgende", pos: "adj", en: "next", source: "curated" },
  { lemma: "eerste", pos: "num", en: "first", source: "curated" },
  { lemma: "nodig", pos: "adj", en: "necessary", source: "curated" },
  { lemma: "vlakbij", pos: "adv", en: "close by", source: "curated" },
  { lemma: "ver", pos: "adj", en: "far", source: "curated" },
  { lemma: "rechtdoor", pos: "adv", en: "straight ahead", source: "curated" },
  { lemma: "links", pos: "adv", en: "left", source: "curated" },
  { lemma: "rechts", pos: "adv", en: "right", source: "curated" },
  { lemma: "dichtstbijzijnde", pos: "adj", en: "nearest", source: "curated" },
  { lemma: "medium", pos: "adj", en: "medium", source: "curated" },

  // Prepositions
  { lemma: "in", pos: "prep", en: "in", source: "curated" },
  { lemma: "uit", pos: "prep", en: "from / out", source: "curated" },
  { lemma: "met", pos: "prep", en: "with", source: "curated" },
  { lemma: "voor", pos: "prep", en: "for / in front of", source: "curated" },
  { lemma: "bij", pos: "prep", en: "at / near", source: "curated" },
  { lemma: "van", pos: "prep", en: "of / from", source: "curated" },
  { lemma: "om", pos: "prep", en: "at / around", source: "curated" },
  { lemma: "op", pos: "prep", en: "on", source: "curated" },
  { lemma: "aan", pos: "prep", en: "at / to", source: "curated" },
  { lemma: "tot", pos: "prep", en: "until", source: "curated" },
  { lemma: "te", pos: "prep", en: "to (with infinitive)", source: "curated" },
  { lemma: "door", pos: "prep", en: "through / by", source: "curated" },
  { lemma: "mee", pos: "adv", en: "along / with", source: "curated" },
  { lemma: "buiten", pos: "prep", en: "outside", source: "curated" },

  // Greetings and politeness
  { lemma: "hoi", pos: "interj", en: "hi", source: "curated" },
  { lemma: "doei", pos: "interj", en: "bye", source: "curated" },
  { lemma: "dag", pos: "noun", article: "de", plural: "dagen", en: "day / hello", source: "curated" },
  { lemma: "goedemorgen", pos: "interj", en: "good morning", source: "curated" },
  { lemma: "goedemiddag", pos: "interj", en: "good afternoon", source: "curated" },
  { lemma: "goedenavond", pos: "interj", en: "good evening", source: "curated" },
  { lemma: "aangenaam", pos: "adj", en: "pleased to meet you", source: "curated" },
  { lemma: "alstublieft", pos: "interj", en: "please / here you are (formal)", source: "curated" },
  { lemma: "alsjeblieft", pos: "interj", en: "please / here you are (informal)", source: "curated" },
  { lemma: "dank", pos: "noun", article: "de", en: "thanks", source: "curated" },
  { lemma: "sorry", pos: "interj", en: "sorry", source: "curated" },
  { lemma: "pardon", pos: "interj", en: "excuse me", source: "curated" },
  { lemma: "ziens", pos: "noun", en: "seeing (bound form, only in \"tot ziens\")", flags: ["bound"], source: "curated" },
  { lemma: "ah", pos: "interj", en: "ah", source: "curated" },

  // ── Verbs ─────────────────────────────────────────────────────────────────
  {
    lemma: "zijn",
    pos: "verb",
    en: "to be",
    participle: "geweest",
    flags: ["irregular"],
    forms: ["ben", "bent", "is", "was", "waren"],
    source: "curated",
  },
  {
    lemma: "hebben",
    pos: "verb",
    en: "to have",
    participle: "gehad",
    flags: ["irregular"],
    forms: ["heb", "hebt", "heeft", "had", "hadden"],
    source: "curated",
  },
  {
    lemma: "gaan",
    pos: "verb",
    en: "to go",
    participle: "gegaan",
    flags: ["irregular"],
    forms: ["ga", "gaat", "ging", "gingen"],
    source: "curated",
  },
  { lemma: "heten", pos: "verb", en: "to be called", participle: "geheten", forms: ["heet"], source: "curated" },
  { lemma: "komen", pos: "verb", en: "to come", participle: "gekomen", flags: ["irregular"], forms: ["kom", "komt", "kwam", "kwamen"], source: "curated" },
  { lemma: "wonen", pos: "verb", en: "to live / reside", participle: "gewoond", forms: ["woon", "woont", "woonde", "woonden"], source: "curated" },
  { lemma: "spreken", pos: "verb", en: "to speak", participle: "gesproken", flags: ["irregular"], forms: ["spreek", "spreekt"], source: "curated" },
  { lemma: "praten", pos: "verb", en: "to talk", participle: "gepraat", forms: ["praat", "praatte", "praatten"], source: "curated" },
  { lemma: "zeggen", pos: "verb", en: "to say", participle: "gezegd", forms: ["zeg", "zegt", "zei", "zeiden"], source: "curated" },
  { lemma: "doen", pos: "verb", en: "to do", participle: "gedaan", flags: ["irregular"], forms: ["doe", "doet", "deed", "deden"], source: "curated" },
  { lemma: "begrijpen", pos: "verb", en: "to understand", participle: "begrepen", flags: ["irregular"], forms: ["begrijp", "begrijpt"], source: "curated" },
  { lemma: "betekenen", pos: "verb", en: "to mean", participle: "betekend", forms: ["betekent"], source: "curated" },
  { lemma: "herhalen", pos: "verb", en: "to repeat", participle: "herhaald", forms: ["herhaal", "herhaalt"], source: "curated" },
  { lemma: "kunnen", pos: "verb", en: "can / to be able", participle: "gekund", flags: ["modal", "irregular"], forms: ["kan", "kun", "kunt"], source: "curated" },
  { lemma: "mogen", pos: "verb", en: "may / to be allowed", participle: "gemogen", flags: ["modal", "irregular"], forms: ["mag"], source: "curated" },
  { lemma: "willen", pos: "verb", en: "to want", participle: "gewild", flags: ["modal", "irregular"], forms: ["wil", "wilt"], source: "curated" },
  { lemma: "moeten", pos: "verb", en: "must / to have to", participle: "gemoeten", flags: ["modal", "irregular"], forms: ["moet"], source: "curated" },
  { lemma: "zullen", pos: "verb", en: "shall / will", flags: ["modal", "irregular"], forms: ["zal", "zult"], source: "curated" },
  { lemma: "kosten", pos: "verb", en: "to cost", participle: "gekost", forms: ["kost"], source: "curated" },
  { lemma: "pinnen", pos: "verb", en: "to pay by debit card", participle: "gepind", forms: ["pin", "pint"], source: "curated" },
  { lemma: "nemen", pos: "verb", en: "to take", participle: "genomen", flags: ["irregular"], forms: ["neem", "neemt", "nam", "namen"], source: "curated" },
  { lemma: "meenemen", pos: "verb", en: "to take along", participle: "meegenomen", flags: ["separable"], source: "curated" },
  { lemma: "zoeken", pos: "verb", en: "to look for", participle: "gezocht", flags: ["irregular"], forms: ["zoek", "zoekt"], source: "curated" },
  { lemma: "passen", pos: "verb", en: "to try on / to fit", participle: "gepast", forms: ["pas", "past"], source: "curated" },
  { lemma: "kijken", pos: "verb", en: "to look", participle: "gekeken", flags: ["irregular"], forms: ["kijk", "kijkt"], source: "curated" },
  { lemma: "helpen", pos: "verb", en: "to help", participle: "geholpen", flags: ["irregular"], forms: ["help", "helpt"], source: "curated" },
  { lemma: "blijven", pos: "verb", en: "to stay", participle: "gebleven", flags: ["irregular"], forms: ["blijf", "blijft"], source: "curated" },
  { lemma: "lachen", pos: "verb", en: "to laugh", participle: "gelachen", forms: ["lach", "lacht"], source: "curated" },
  { lemma: "groeien", pos: "verb", en: "to grow", participle: "gegroeid", forms: ["groei", "groeit"], source: "curated" },
  { lemma: "staan", pos: "verb", en: "to stand", participle: "gestaan", flags: ["irregular"], forms: ["sta", "staat"], source: "curated" },
  { lemma: "opschrijven", pos: "verb", en: "to write down", participle: "opgeschreven", flags: ["separable", "irregular"], source: "curated" },
  { lemma: "doorsturen", pos: "verb", en: "to forward", participle: "doorgestuurd", flags: ["separable"], forms: ["stuur"], source: "curated" },
  { lemma: "terugkomen", pos: "verb", en: "to come back", participle: "teruggekomen", flags: ["separable", "irregular"], source: "curated" },
  { lemma: "roepen", pos: "verb", en: "to call", participle: "geroepen", flags: ["irregular"], forms: ["roep", "roept"], source: "curated" },
  { lemma: "zien", pos: "verb", en: "to see", participle: "gezien", flags: ["irregular"], forms: ["zie", "ziet", "zag", "zagen"], source: "curated" },
  { lemma: "lezen", pos: "verb", en: "to read", participle: "gelezen", flags: ["irregular"], forms: ["lees", "leest", "las", "lazen"], source: "curated" },
  { lemma: "drinken", pos: "verb", en: "to drink", participle: "gedronken", flags: ["irregular"], forms: ["drink", "drinkt"], source: "curated" },
  { lemma: "vallen", pos: "verb", en: "to fall", participle: "gevallen", flags: ["irregular"], forms: ["val", "valt", "viel"], source: "curated" },
  { lemma: "regenen", pos: "verb", en: "to rain", participle: "geregend", forms: ["regent", "regende"], source: "curated" },
  { lemma: "worden", pos: "verb", en: "to become", participle: "geworden", flags: ["irregular"], forms: ["word", "wordt", "werd"], source: "curated" },
  { lemma: "verdwalen", pos: "verb", en: "to get lost", participle: "verdwaald", forms: ["verdwaal", "verdwaalt"], source: "curated" },

  // ── Adjectives ────────────────────────────────────────────────────────────
  { lemma: "goed", pos: "adj", en: "good", forms: ["goede", "goet"], source: "curated" },
  { lemma: "leuk", pos: "adj", en: "nice / fun", forms: ["leuke"], source: "curated" },
  { lemma: "mooi", pos: "adj", en: "beautiful", source: "curated" },
  { lemma: "blauw", pos: "adj", en: "blue", forms: ["blauwe"], source: "curated" },
  { lemma: "klein", pos: "adj", en: "small", forms: ["kleine"], source: "curated" },
  { lemma: "gezellig", pos: "adj", en: "cosy / convivial", source: "curated" },
  { lemma: "groen", pos: "adj", en: "green", source: "curated" },
  { lemma: "vuil", pos: "adj", en: "dirty", forms: ["vuile"], source: "curated" },
  { lemma: "langzaam", pos: "adj", en: "slow", forms: ["langzamer"], source: "curated" },
  { lemma: "goedkoop", pos: "adj", en: "cheap", forms: ["goedkopers", "goedkoper"], source: "curated" },
  { lemma: "veel", pos: "adj", en: "much / many", forms: ["meer"], source: "curated" },
  { lemma: "heel", pos: "adj", en: "whole / very", source: "curated" },

  // ── Numbers ───────────────────────────────────────────────────────────────
  { lemma: "twee", pos: "num", en: "two", source: "curated" },
  { lemma: "drie", pos: "num", en: "three", source: "curated" },
  { lemma: "vier", pos: "num", en: "four", source: "curated" },
  { lemma: "vijf", pos: "num", en: "five", source: "curated" },
  { lemma: "acht", pos: "num", en: "eight", source: "curated" },
  { lemma: "vijftig", pos: "num", en: "fifty", source: "curated" },

  // ── Nouns ─────────────────────────────────────────────────────────────────
  { lemma: "koffie", pos: "noun", article: "de", en: "coffee", source: "curated" },
  { lemma: "thee", pos: "noun", article: "de", en: "tea", source: "curated" },
  { lemma: "biertje", pos: "noun", article: "het", plural: "biertjes", en: "beer (small)", flags: ["diminutive"], source: "curated" },
  { lemma: "broodje", pos: "noun", article: "het", plural: "broodjes", en: "bread roll", flags: ["diminutive"], source: "curated" },
  { lemma: "kaas", pos: "noun", article: "de", plural: "kazen", en: "cheese", source: "curated" },
  { lemma: "glas", pos: "noun", article: "het", plural: "glazen", en: "glass", source: "curated" },
  { lemma: "water", pos: "noun", article: "het", en: "water", source: "curated" },
  { lemma: "melk", pos: "noun", article: "de", en: "milk", source: "curated" },
  { lemma: "wijn", pos: "noun", article: "de", plural: "wijnen", en: "wine", source: "curated" },
  { lemma: "citroen", pos: "noun", article: "de", plural: "citroenen", en: "lemon", source: "curated" },
  { lemma: "aardbei", pos: "noun", article: "de", plural: "aardbeien", en: "strawberry", source: "curated" },
  { lemma: "perzik", pos: "noun", article: "de", plural: "perziken", en: "peach", source: "curated" },
  { lemma: "knoflook", pos: "noun", article: "de", en: "garlic", source: "curated" },
  { lemma: "boodschap", pos: "noun", article: "de", plural: "boodschappen", en: "errand / grocery item", source: "curated" },
  { lemma: "kaart", pos: "noun", article: "de", plural: "kaarten", en: "menu / card", source: "curated" },
  { lemma: "rekening", pos: "noun", article: "de", plural: "rekeningen", en: "bill", source: "curated" },
  { lemma: "euro", pos: "noun", article: "de", plural: "euro's", en: "euro", source: "curated" },
  { lemma: "station", pos: "noun", article: "het", plural: "stations", en: "station", source: "curated" },
  { lemma: "museum", pos: "noun", article: "het", plural: "musea", en: "museum", source: "curated" },
  { lemma: "supermarkt", pos: "noun", article: "de", plural: "supermarkten", en: "supermarket", source: "curated" },
  { lemma: "toilet", pos: "noun", article: "het", plural: "toiletten", en: "toilet", source: "curated" },
  { lemma: "halte", pos: "noun", article: "de", plural: "haltes", en: "stop", source: "curated" },
  { lemma: "straat", pos: "noun", article: "de", plural: "straten", en: "street", source: "curated" },
  { lemma: "hoek", pos: "noun", article: "de", plural: "hoeken", en: "corner", source: "curated" },
  { lemma: "cadeau", pos: "noun", article: "het", plural: "cadeaus", en: "gift", source: "curated" },
  { lemma: "jas", pos: "noun", article: "de", plural: "jassen", en: "coat", source: "curated" },
  { lemma: "raam", pos: "noun", article: "het", plural: "ramen", en: "window", source: "curated" },
  { lemma: "kilo", pos: "noun", article: "de", plural: "kilo's", en: "kilo", source: "curated" },
  { lemma: "maat", pos: "noun", article: "de", plural: "maten", en: "size", source: "curated" },
  { lemma: "huis", pos: "noun", article: "het", plural: "huizen", en: "house", source: "curated" },
  { lemma: "deur", pos: "noun", article: "de", plural: "deuren", en: "door", source: "curated" },
  { lemma: "keuken", pos: "noun", article: "de", plural: "keukens", en: "kitchen", source: "curated" },
  { lemma: "kleur", pos: "noun", article: "de", plural: "kleuren", en: "colour", source: "curated" },
  { lemma: "neus", pos: "noun", article: "de", plural: "neuzen", en: "nose", source: "curated" },
  { lemma: "boek", pos: "noun", article: "het", plural: "boeken", en: "book", source: "curated" },
  { lemma: "vuur", pos: "noun", article: "het", plural: "vuren", en: "fire", source: "curated" },
  { lemma: "buur", pos: "noun", article: "de", plural: "buren", en: "neighbour", forms: ["buurman"], source: "curated" },
  { lemma: "duim", pos: "noun", article: "de", plural: "duimen", en: "thumb", source: "curated" },
  { lemma: "muis", pos: "noun", article: "de", plural: "muizen", en: "mouse", source: "curated" },
  { lemma: "trein", pos: "noun", article: "de", plural: "treinen", en: "train", source: "curated" },
  { lemma: "tijd", pos: "noun", article: "de", plural: "tijden", en: "time", forms: ["tijdje"], source: "curated" },
  { lemma: "zee", pos: "noun", article: "de", plural: "zeeën", en: "sea", source: "curated" },
  { lemma: "mier", pos: "noun", article: "de", plural: "mieren", en: "ant", source: "curated" },
  { lemma: "vader", pos: "noun", article: "de", plural: "vaders", en: "father", source: "curated" },
  { lemma: "mens", pos: "noun", article: "de", plural: "mensen", en: "person", source: "curated" },
  { lemma: "werk", pos: "noun", article: "het", en: "work", source: "curated" },
  { lemma: "naam", pos: "noun", article: "de", plural: "namen", en: "name", source: "curated" },
  { lemma: "jaar", pos: "noun", article: "het", plural: "jaren", en: "year", source: "curated" },
  { lemma: "week", pos: "noun", article: "de", plural: "weken", en: "week", source: "curated" },
  { lemma: "minuut", pos: "noun", article: "de", plural: "minuten", en: "minute", source: "curated" },
  { lemma: "morgen", pos: "noun", article: "de", en: "morning / tomorrow", forms: ["morgens"], source: "curated" },
  { lemma: "avond", pos: "noun", article: "de", plural: "avonden", en: "evening", forms: ["avonds"], source: "curated" },
  { lemma: "moment", pos: "noun", article: "het", plural: "momenten", en: "moment", forms: ["momentje"], source: "curated" },
  { lemma: "weer", pos: "noun", article: "het", en: "weather / again", source: "curated" },
  { lemma: "beetje", pos: "noun", article: "het", en: "a little", flags: ["diminutive"], source: "curated" },
  { lemma: "gras", pos: "noun", article: "het", en: "grass", source: "curated" },
  { lemma: "engels", pos: "noun", article: "het", en: "English", source: "curated" },
  { lemma: "nederlands", pos: "noun", article: "het", en: "Dutch", source: "curated" },

  // ── Proper nouns ──────────────────────────────────────────────────────────
  { lemma: "josh", pos: "name", en: "Josh", source: "curated" },
  { lemma: "sanne", pos: "name", en: "Sanne", source: "curated" },
  { lemma: "amsterdam", pos: "name", en: "Amsterdam", source: "curated" },
  { lemma: "rotterdam", pos: "name", en: "Rotterdam", source: "curated" },
  { lemma: "engeland", pos: "name", en: "England", source: "curated" },
  { lemma: "amerika", pos: "name", en: "America", source: "curated" },
  { lemma: "oeganda", pos: "name", en: "Uganda", source: "curated" },
  { lemma: "afrika", pos: "name", en: "Africa", source: "curated" },
  { lemma: "zuid", pos: "name", en: "South", forms: ["zuid-afrika"], source: "curated" },
];
