import type { LexiconEntry } from "@/lib/types";

/**
 * GENERATED — do not edit by hand.
 * Rebuild with: npx tsx scripts/build-lexicon.ts nl
 *
 * Derived from Wiktionary via kaikki.org. This data is licensed CC BY-SA 4.0;
 * see docs/ATTRIBUTION.md. Hand-written entries live in lexicon.ts and take
 * precedence over anything here.
 */
export const generatedLexicon: LexiconEntry[] = [
  { lemma: "aanbevelen", pos: "verb", en: "to recommend", participle: "aanbevolen", source: "wiktionary" },
  { lemma: "aap", pos: "noun", en: "monkey, ape, simian; any member of the infraorder Simiiformes", article: "de", plural: "apen", forms: ["apen"], source: "wiktionary" },
  { lemma: "aardappel", pos: "noun", en: "potato (tuber eaten as vegetable)", article: "de", forms: ["aardappels"], source: "wiktionary" },
  { lemma: "achterin", pos: "adv", en: "in the back/rear", source: "wiktionary" },
  { lemma: "af", pos: "adv", en: "off", source: "wiktionary" },
  { lemma: "afspreken", pos: "verb", en: "to agree, to make an agreement", participle: "afgesproken", source: "wiktionary" },
  { lemma: "allergisch", pos: "adj", en: "allergic", source: "wiktionary" },
  { lemma: "alles", pos: "pron", en: "everything", source: "wiktionary" },
  { lemma: "appartement", pos: "noun", en: "an apartment", article: "het", source: "wiktionary" },
  { lemma: "appel", pos: "noun", en: "apple (Malus domestica, fruit or tree)", article: "de", plural: "appels", forms: ["appels"], source: "wiktionary" },
  { lemma: "arm", pos: "noun", en: "arm", article: "de", plural: "armen", forms: ["armen"], source: "wiktionary" },
  { lemma: "atten", pos: "verb", en: "to empty a glass by drinking it in one draught; to down, to chug", participle: "geat", forms: ["at"], source: "wiktionary" },
  { lemma: "eten", pos: "verb", en: "to eat", participle: "gegeten", forms: ["eet","at","aten","gegeten"], source: "wiktionary" },
  { lemma: "auto", pos: "noun", en: "car, automobile", article: "de", source: "wiktionary" },
  { lemma: "badkamer", pos: "noun", en: "bathroom", article: "de", plural: "badkamers", forms: ["badkamers"], source: "wiktionary" },
  { lemma: "balkon", pos: "noun", en: "balcony", article: "het", source: "wiktionary" },
  { lemma: "banaan", pos: "noun", en: "banana", article: "de", plural: "bananen", forms: ["bananen"], source: "wiktionary" },
  { lemma: "bed", pos: "noun", en: "bed (furniture for sleeping)", article: "het", plural: "bedden", forms: ["bedden"], source: "wiktionary" },
  { lemma: "been", pos: "noun", en: "leg, limb of a person, horse (other animals would have poten) and certain objects (again many have poten)", article: "het", plural: "benen", forms: ["benen"], source: "wiktionary" },
  { lemma: "beer", pos: "noun", en: "a bear, any member of the family Ursidae", article: "de", plural: "beren", forms: ["beren"], source: "wiktionary" },
  { lemma: "beginnen", pos: "verb", en: "to begin", participle: "begonnen", forms: ["begon","begint","begonnen"], source: "wiktionary" },
  { lemma: "benen", pos: "adj", en: "made of bone", source: "wiktionary" },
  { lemma: "best", pos: "adj", en: "fine, okay", source: "wiktionary" },
  { lemma: "bestellen", pos: "verb", en: "to order, demand delivery", participle: "besteld", source: "wiktionary" },
  { lemma: "betalen", pos: "verb", en: "to pay", participle: "betaald", forms: ["betaal","betaalde","betaald"], source: "wiktionary" },
  { lemma: "betaald", pos: "adj", en: "nonfree, paid, for payment", source: "wiktionary" },
  { lemma: "beter", pos: "adj", en: "not sick anymore; recovered (from a disease)", source: "wiktionary" },
  { lemma: "bier", pos: "noun", en: "beer (alcoholic drink brewed from grains or other starch material)", article: "het", plural: "bieren", forms: ["bieren","biertje"], source: "wiktionary" },
  { lemma: "bij", pos: "noun", en: "bee, insect of the clade Anthophila", article: "de", plural: "bijen", forms: ["bijen"], source: "wiktionary" },
  { lemma: "binnen", pos: "adv", en: "inside, indoors", source: "wiktionary" },
  { lemma: "bonnetje", pos: "noun", en: "receipt (diminutive)", article: "het", flags: ["diminutive"], source: "wiktionary" },
  { lemma: "boter", pos: "noun", en: "butter, a spread made from churned milk", article: "de", source: "wiktionary" },
  { lemma: "boterham", pos: "noun", en: "a slice of bread", article: "de", plural: "boterhammen", forms: ["boterhammen"], source: "wiktionary" },
  { lemma: "brief", pos: "noun", en: "letter (written message)", article: "de", source: "wiktionary" },
  { lemma: "brood", pos: "noun", en: "bread", article: "het", plural: "broden", forms: ["broden","broodje"], source: "wiktionary" },
  { lemma: "broer", pos: "noun", en: "brother (male sibling)", article: "de", plural: "broers", forms: ["broers"], source: "wiktionary" },
  { lemma: "bruin", pos: "adj", en: "brown", source: "wiktionary" },
  { lemma: "buik", pos: "noun", en: "belly", article: "de", plural: "buiken", forms: ["buiken"], source: "wiktionary" },
  { lemma: "bus", pos: "noun", en: "bus, omnibus (vehicle)", article: "de", source: "wiktionary" },
  { lemma: "champignon", pos: "noun", en: "a champignon, a button mushroom, Agaricus bisporus", article: "de", plural: "champignons", forms: ["champignons"], source: "wiktionary" },
  { lemma: "chocolade", pos: "noun", en: "chocolate", article: "de", source: "wiktionary" },
  { lemma: "contant", pos: "adj", en: "in cash", source: "wiktionary" },
  { lemma: "daar", pos: "adv", en: "there", source: "wiktionary" },
  { lemma: "na", pos: "prep", en: "after", forms: ["daarna"], source: "wiktionary" },
  { lemma: "den", pos: "noun", en: "pine, pine tree", article: "de", source: "wiktionary" },
  { lemma: "denken", pos: "verb", en: "to think", participle: "gedacht", source: "wiktionary" },
  { lemma: "dertien", pos: "num", en: "thirteen", source: "wiktionary" },
  { lemma: "dertig", pos: "num", en: "thirty", source: "wiktionary" },
  { lemma: "deze", pos: "det", en: "this; referring to a thing or a person closer by.", forms: ["dit"], source: "wiktionary" },
  { lemma: "die", pos: "det", en: "that; referring to a thing or a person further away.", forms: ["dat"], source: "wiktionary" },
  { lemma: "dinsdag", pos: "noun", en: "Tuesday", article: "de", source: "wiktionary" },
  { lemma: "dochter", pos: "noun", en: "daughter (female offspring)", article: "de", plural: "dochters", forms: ["dochters"], source: "wiktionary" },
  { lemma: "donderdag", pos: "noun", en: "Thursday", article: "de", source: "wiktionary" },
  { lemma: "dronk", pos: "noun", en: "drink; draught", article: "de", plural: "dronken", forms: ["dronken"], source: "wiktionary" },
  { lemma: "dronken", pos: "adj", en: "drunk, drunken, in a state of intoxication after drinking alcohol beverages", source: "wiktionary" },
  { lemma: "druif", pos: "noun", en: "grape", article: "de", plural: "druiven", forms: ["druiven"], source: "wiktionary" },
  { lemma: "duur", pos: "adj", en: "expensive, dear", source: "wiktionary" },
  { lemma: "eend", pos: "noun", en: "A Citroën 2CV car.", article: "de", plural: "eenden", forms: ["eenden"], source: "wiktionary" },
  { lemma: "eenentwintig", pos: "num", en: "twenty-one", source: "wiktionary" },
  { lemma: "eerlijk", pos: "adj", en: "honest", source: "wiktionary" },
  { lemma: "ei", pos: "noun", en: "egg", article: "het", plural: "eieren", forms: ["eieren"], source: "wiktionary" },
  { lemma: "elf", pos: "num", en: "eleven", source: "wiktionary" },
  { lemma: "elk", pos: "det", en: "each; every", forms: ["elke"], source: "wiktionary" },
  { lemma: "enkele", pos: "pron", en: "a few, some", source: "wiktionary" },
  { lemma: "er", pos: "adv", en: "there (can refer to any place, used when not emphasizing the distance to the speaker, see usage notes)", source: "wiktionary" },
  { lemma: "over", pos: "prep", en: "over", forms: ["erover"], source: "wiktionary" },
  { lemma: "fiets", pos: "noun", en: "bicycle", article: "de", plural: "fietsen", forms: ["fietsen"], source: "wiktionary" },
  { lemma: "fietsen", pos: "verb", en: "to ride or cycle a bicycle, to bike", participle: "gefietst", forms: ["fiets","fietsten","gefietst"], source: "wiktionary" },
  { lemma: "fijn", pos: "adj", en: "nice, pleasant", forms: ["fijne"], source: "wiktionary" },
  { lemma: "film", pos: "noun", en: "a film, thin layer or membrane; especially the physical medium film", article: "de", source: "wiktionary" },
  { lemma: "foto", pos: "noun", en: "photo, photograph", article: "de", plural: "foto's", forms: ["foto's"], source: "wiktionary" },
  { lemma: "frisdrank", pos: "noun", en: "a soda, soft drink", article: "de", source: "wiktionary" },
  { lemma: "fruit", pos: "noun", en: "fruit (produced by trees or bushes, or any sweet vegetable; only literal sense)", article: "het", source: "wiktionary" },
  { lemma: "geven", pos: "verb", en: "to give", participle: "gegeven", forms: ["geef","gaf","gaven","gegeven"], source: "wiktionary" },
  { lemma: "gave", pos: "noun", en: "a gift, donation, present", article: "de", plural: "gaven", forms: ["gaven"], source: "wiktionary" },
  { lemma: "geef", pos: "noun", en: "gift", article: "de", plural: "geven", forms: ["geven"], source: "wiktionary" },
  { lemma: "geel", pos: "adj", en: "yellow", source: "wiktionary" },
  { lemma: "gegeven", pos: "adj", en: "given, determined, known", source: "wiktionary" },
  { lemma: "geit", pos: "noun", en: "goat, any member of the genus Capra", article: "de", plural: "geiten", forms: ["geiten"], source: "wiktionary" },
  { lemma: "geiten", pos: "verb", en: "to act girlishly, esp. to giggle a lot", participle: "gegeit", forms: ["geit"], source: "wiktionary" },
  { lemma: "kopen", pos: "verb", en: "to buy, purchase", participle: "gekocht", forms: ["koop","kocht","kochten","gekocht"], source: "wiktionary" },
  { lemma: "koken", pos: "verb", en: "to cook, boil", participle: "gekookt", forms: ["kook","kookte","gekookt"], source: "wiktionary" },
  { lemma: "geld", pos: "noun", en: "money", article: "het", source: "wiktionary" },
  { lemma: "geleerd", pos: "adj", en: "learned", source: "wiktionary" },
  { lemma: "lopen", pos: "verb", en: "to run, go fast on one's own legs", participle: "gelopen", forms: ["loop","liep","liepen","gelopen"], source: "wiktionary" },
  { lemma: "luisteren", pos: "verb", en: "to listen", participle: "geluisterd", forms: ["luister","luisterden","geluisterd"], source: "wiktionary" },
  { lemma: "geluk", pos: "noun", en: "luck, good luck", article: "het", source: "wiktionary" },
  { lemma: "gemaakt", pos: "adj", en: "artificial, unnatural", source: "wiktionary" },
  { lemma: "reserveren", pos: "verb", en: "to reserve", participle: "gereserveerd", forms: ["gereserveerd"], source: "wiktionary" },
  { lemma: "schrijven", pos: "verb", en: "to write", participle: "geschreven", forms: ["schrijf","schreef","schreven","geschreven"], source: "wiktionary" },
  { lemma: "slapen", pos: "verb", en: "to sleep", participle: "geslapen", forms: ["sliep","slaapt","sliepen","geslapen"], source: "wiktionary" },
  { lemma: "spelen", pos: "verb", en: "to play", participle: "gespeeld", forms: ["speelt","speelden","gespeeld"], source: "wiktionary" },
  { lemma: "getrouwd", pos: "adj", en: "married", source: "wiktionary" },
  { lemma: "vinden", pos: "verb", en: "to find (after searching)", participle: "gevonden", forms: ["vind","vond","vonden","gevonden"], source: "wiktionary" },
  { lemma: "werken", pos: "verb", en: "to work, labour", participle: "gewerkt", forms: ["werk","werkte","werkt","gewerkt"], source: "wiktionary" },
  { lemma: "gisteren", pos: "adv", en: "yesterday", source: "wiktionary" },
  { lemma: "graad", pos: "noun", en: "degree", article: "de", plural: "graden", forms: ["graden"], source: "wiktionary" },
  { lemma: "grijs", pos: "adj", en: "grey, grey-colored", source: "wiktionary" },
  { lemma: "groente", pos: "noun", en: "vegetables", article: "de", plural: "groenten", forms: ["groenten"], source: "wiktionary" },
  { lemma: "groot", pos: "adj", en: "big, large, great", forms: ["grote"], source: "wiktionary" },
  { lemma: "Haag", pos: "name", en: "a hamlet in Venray, Limburg, Netherlands", source: "wiktionary" },
  { lemma: "haan", pos: "noun", en: "a cock, a rooster (male chicken)", article: "de", plural: "hanen", forms: ["hanen"], source: "wiktionary" },
  { lemma: "haar", pos: "pron", en: "her; third-person singular feminine objective personal pronoun", source: "wiktionary" },
  { lemma: "half", pos: "adj", en: "half", source: "wiktionary" },
  { lemma: "hand", pos: "noun", en: "a hand of a human, other simian or other animal with fingers", article: "de", plural: "handen", forms: ["handen"], source: "wiktionary" },
  { lemma: "hap", pos: "noun", en: "bite", article: "de", source: "wiktionary" },
  { lemma: "hard", pos: "adj", en: "hard, strong", source: "wiktionary" },
  { lemma: "heerlijk", pos: "adj", en: "wonderful (when referring to a sensation), great", source: "wiktionary" },
  { lemma: "hele", pos: "adv", en: "alternative form of heel", source: "wiktionary" },
  { lemma: "hem", pos: "pron", en: "him; third-person singular masculine objective personal pronoun", source: "wiktionary" },
  { lemma: "hetzelfde", pos: "adv", en: "the same", source: "wiktionary" },
  { lemma: "hij", pos: "pron", en: "he; third-person singular masculine subjective personal pronoun", source: "wiktionary" },
  { lemma: "hond", pos: "noun", en: "dog (Canis lupus familiaris)", article: "de", plural: "honden", forms: ["honden"], source: "wiktionary" },
  { lemma: "honderd", pos: "num", en: "hundred", source: "wiktionary" },
  { lemma: "honger", pos: "noun", en: "hunger", article: "de", source: "wiktionary" },
  { lemma: "honing", pos: "noun", en: "honey", article: "de", source: "wiktionary" },
  { lemma: "hoofd", pos: "noun", en: "head", article: "het", plural: "hoofden", forms: ["hoofden"], source: "wiktionary" },
  { lemma: "houden", pos: "verb", en: "to keep, preserve", participle: "gehouden", source: "wiktionary" },
  { lemma: "huiswerk", pos: "noun", en: "homework (educational assignment to be done in one's own time)", article: "het", source: "wiktionary" },
  { lemma: "hè", pos: "interj", en: "huh; said when surprised or puzzled.", source: "wiktionary" },
  { lemma: "ijs", pos: "noun", en: "ice (frozen liquid, notably water)", article: "het", source: "wiktionary" },
  { lemma: "ja", pos: "adv", en: "yes", source: "wiktionary" },
  { lemma: "kaartje", pos: "noun", en: "ticket, especially a train ticket (diminutive)", article: "het", flags: ["diminutive"], source: "wiktionary" },
  { lemma: "kamer", pos: "noun", en: "a room, physical chamber in a building", article: "de", plural: "kamers", forms: ["kamers"], source: "wiktionary" },
  { lemma: "kassa", pos: "noun", en: "cash desk, checkout", article: "de", source: "wiktionary" },
  { lemma: "kat", pos: "noun", en: "domestic cat, pussy, Felis silvestris catus", article: "de", plural: "katten", forms: ["katten"], source: "wiktionary" },
  { lemma: "katten", pos: "verb", en: "to slate, to criticise heavily, in a snide manner", participle: "gekat", forms: ["kat"], source: "wiktionary" },
  { lemma: "kennen", pos: "verb", en: "to know, experience", participle: "gekend", source: "wiktionary" },
  { lemma: "kilometer", pos: "noun", en: "kilometre", article: "de", source: "wiktionary" },
  { lemma: "kind", pos: "noun", en: "child, kid, non-adult human", article: "het", plural: "kinderen", forms: ["kinderen"], source: "wiktionary" },
  { lemma: "kip", pos: "noun", en: "a chicken, Gallus gallus domesticus", article: "de", plural: "kippen", forms: ["kippen"], source: "wiktionary" },
  { lemma: "kleingeld", pos: "noun", en: "small change", article: "het", source: "wiktionary" },
  { lemma: "koe", pos: "noun", en: "cow; a female of certain mammals, in particular bovines", article: "de", plural: "koeien", forms: ["koeien"], source: "wiktionary" },
  { lemma: "koek", pos: "noun", en: "cookie, cake, biscuit, wafer", article: "de", plural: "koeken", forms: ["koeken"], source: "wiktionary" },
  { lemma: "koeken", pos: "noun", en: "diamonds", source: "wiktionary" },
  { lemma: "komkommer", pos: "noun", en: "cucumber", article: "de", plural: "komkommers", forms: ["komkommers"], source: "wiktionary" },
  { lemma: "konijn", pos: "noun", en: "a rabbit, a bunny; any non-hare lagomorph of the family Leporidae", article: "het", plural: "konijnen", forms: ["konijnen"], source: "wiktionary" },
  { lemma: "koop", pos: "noun", en: "a purchase, bought acquisition", article: "de", plural: "kopen", forms: ["kopen"], source: "wiktionary" },
  { lemma: "korting", pos: "noun", en: "discount", article: "de", source: "wiktionary" },
  { lemma: "koud", pos: "adj", en: "cold (temperature)", source: "wiktionary" },
  { lemma: "krant", pos: "noun", en: "newspaper", article: "de", source: "wiktionary" },
  { lemma: "kwart", pos: "noun", en: "a quarter, one of four (equal) parts", article: "het", source: "wiktionary" },
  { lemma: "laat", pos: "adj", en: "late (not early)", forms: ["later"], source: "wiktionary" },
  { lemma: "lang", pos: "adj", en: "long", source: "wiktionary" },
  { lemma: "leer", pos: "noun", en: "leather", article: "het", source: "wiktionary" },
  { lemma: "leren", pos: "verb", en: "to learn, to study", participle: "geleerd", forms: ["leer","leerde","geleerd"], source: "wiktionary" },
  { lemma: "leeuw", pos: "noun", en: "lion", article: "de", plural: "leeuwen", forms: ["leeuwen"], source: "wiktionary" },
  { lemma: "Leeuwen", pos: "name", en: "a village in Roermond, Limburg, Netherlands", source: "wiktionary" },
  { lemma: "lekker", pos: "adj", en: "having a nice taste, tasty, delectable", forms: ["lekkers"], source: "wiktionary" },
  { lemma: "lekkers", pos: "noun", en: "sweets, treats", article: "het", source: "wiktionary" },
  { lemma: "les", pos: "noun", en: "course, lesson", article: "de", source: "wiktionary" },
  { lemma: "licht", pos: "adj", en: "light, of little weight", source: "wiktionary" },
  { lemma: "loop", pos: "noun", en: "course, duration", article: "de", plural: "lopen", forms: ["lopen"], source: "wiktionary" },
  { lemma: "luister", pos: "noun", en: "lustre/luster, splendor", article: "de", source: "wiktionary" },
  { lemma: "maken", pos: "verb", en: "to make, create, prepare", participle: "gemaakt", forms: ["maak","maakten","gemaakt"], source: "wiktionary" },
  { lemma: "maand", pos: "noun", en: "a month", article: "de", plural: "maanden", forms: ["maanden"], source: "wiktionary" },
  { lemma: "maandag", pos: "noun", en: "Monday", article: "de", source: "wiktionary" },
  { lemma: "mail", pos: "noun", en: "alternative form of e-mail", article: "de", source: "wiktionary" },
  { lemma: "man", pos: "noun", en: "man, human male, either adult or age-irrespective", article: "de", plural: "mannen", forms: ["mannen"], source: "wiktionary" },
  { lemma: "meestal", pos: "adv", en: "most of the time, in most cases, usually", source: "wiktionary" },
  { lemma: "meisje", pos: "noun", en: "girl (especially of a premature age) (diminutive)", article: "het", flags: ["diminutive"], source: "wiktionary" },
  { lemma: "meneer", pos: "noun", en: "sir, mister", article: "de", source: "wiktionary" },
  { lemma: "mevrouw", pos: "noun", en: "madam, miss", article: "de", source: "wiktionary" },
  { lemma: "mij", pos: "pron", en: "me; first-person singular objective personal pronoun", source: "wiktionary" },
  { lemma: "mis", pos: "noun", en: "mass (service in a Catholic church)", article: "de", source: "wiktionary" },
  { lemma: "moe", pos: "adj", en: "tired, weary", source: "wiktionary" },
  { lemma: "moeder", pos: "noun", en: "mother, female parent", article: "de", plural: "moeders", forms: ["moeders","vader"], source: "wiktionary" },
  { lemma: "mond", pos: "noun", en: "mouth", article: "de", plural: "monden", forms: ["monden"], source: "wiktionary" },
  { lemma: "muur", pos: "noun", en: "wall", article: "de", source: "wiktionary" },
  { lemma: "muziek", pos: "noun", en: "music (sound; art)", article: "de", source: "wiktionary" },
  { lemma: "naar", pos: "prep", en: "to, towards in time, space, consequence, purpose etc.", source: "wiktionary" },
  { lemma: "naast", pos: "prep", en: "beside, next to", source: "wiktionary" },
  { lemma: "Nederland", pos: "name", en: "a hamlet in Steenwijkerland, Overijssel, Netherlands", source: "wiktionary" },
  { lemma: "negen", pos: "num", en: "nine", source: "wiktionary" },
  { lemma: "negenennegentig", pos: "num", en: "ninety-nine", source: "wiktionary" },
  { lemma: "negentig", pos: "num", en: "ninety", source: "wiktionary" },
  { lemma: "net", pos: "noun", en: "net (mesh)", article: "het", source: "wiktionary" },
  { lemma: "nieuw", pos: "adj", en: "new", forms: ["nieuwe"], source: "wiktionary" },
  { lemma: "nog", pos: "adv", en: "still, as before", source: "wiktionary" },
  { lemma: "nooit", pos: "adv", en: "never", source: "wiktionary" },
  { lemma: "noot", pos: "noun", en: "nut", article: "de", plural: "noten", forms: ["noten"], source: "wiktionary" },
  { lemma: "nu", pos: "adv", en: "now, at the present moment", source: "wiktionary" },
  { lemma: "nummer", pos: "noun", en: "number used as a means of identification", article: "het", source: "wiktionary" },
  { lemma: "ochtend", pos: "noun", en: "morning", article: "de", source: "wiktionary" },
  { lemma: "ogen", pos: "verb", en: "to look, to appear", participle: "geoogd", forms: ["oog"], source: "wiktionary" },
  { lemma: "olie", pos: "noun", en: "any natural or industrial oil", article: "de", source: "wiktionary" },
  { lemma: "olifant", pos: "noun", en: "elephant", article: "de", plural: "olifanten", forms: ["olifanten"], source: "wiktionary" },
  { lemma: "oma", pos: "noun", en: "grandma, granny, nan", article: "de", plural: "oma's", forms: ["oma's"], source: "wiktionary" },
  { lemma: "ondergaan", pos: "verb", en: "to undergo, endure", participle: "ondergaan", source: "wiktionary" },
  { lemma: "ontbijt", pos: "noun", en: "a breakfast, first meal of the day, usually in the morning", article: "het", source: "wiktionary" },
  { lemma: "oog", pos: "noun", en: "eye", article: "het", plural: "ogen", forms: ["ogen"], source: "wiktionary" },
  { lemma: "oom", pos: "noun", en: "uncle", article: "de", plural: "ooms", forms: ["ooms"], source: "wiktionary" },
  { lemma: "oor", pos: "noun", en: "ear", article: "het", plural: "oren", forms: ["oren"], source: "wiktionary" },
  { lemma: "opa", pos: "noun", en: "granddad, grandpa, pops", article: "de", plural: "opa's", forms: ["opa's"], source: "wiktionary" },
  { lemma: "oplossing", pos: "noun", en: "solution (e.g. to a mathematical problem)", article: "de", source: "wiktionary" },
  { lemma: "oranje", pos: "adj", en: "orange", source: "wiktionary" },
  { lemma: "oud", pos: "adj", en: "old (having existed for a relatively long period of time)", forms: ["ouders"], source: "wiktionary" },
  { lemma: "ouder", pos: "noun", en: "parent, father or mother; by extension a substitute caregiver", article: "de", plural: "ouders", forms: ["ouders"], source: "wiktionary" },
  { lemma: "overstappen", pos: "verb", en: "to transfer (to a different bus or train)", participle: "overgestapt", source: "wiktionary" },
  { lemma: "paard", pos: "noun", en: "horse (Equus caballus or Equus ferus)", article: "het", plural: "paarden", forms: ["paarden"], source: "wiktionary" },
  { lemma: "paars", pos: "adj", en: "purple", source: "wiktionary" },
  { lemma: "paprika", pos: "noun", en: "sweet pepper, bell pepper (plant or fruit of Capsicum annuum varieties yielding sweet peppers)", article: "de", plural: "paprika's", forms: ["paprika's"], source: "wiktionary" },
  { lemma: "Parijs", pos: "name", en: "Paris (the capital and largest city of France)", source: "wiktionary" },
  { lemma: "park", pos: "noun", en: "park", article: "het", source: "wiktionary" },
  { lemma: "pasta", pos: "noun", en: "paste", article: "de", source: "wiktionary" },
  { lemma: "pauze", pos: "noun", en: "pause, break", article: "de", source: "wiktionary" },
  { lemma: "peer", pos: "noun", en: "a pear, a fruit of the pear tree", article: "de", plural: "peren", forms: ["peren"], source: "wiktionary" },
  { lemma: "peper", pos: "noun", en: "pepper (Piper nigrum or the spice obtained from its berries)", article: "de", source: "wiktionary" },
  { lemma: "peren", pos: "verb", en: "To leave abruptly, to bail (out).", participle: "gepeerd", forms: ["peer"], source: "wiktionary" },
  { lemma: "perron", pos: "noun", en: "a boarding platform on which passengers wait for a train: it is next to a spoor", article: "het", source: "wiktionary" },
  { lemma: "pijn", pos: "noun", en: "pain, ache (physical)", article: "de", source: "wiktionary" },
  { lemma: "radio", pos: "noun", en: "radio, tuner", article: "de", source: "wiktionary" },
  { lemma: "rat", pos: "noun", en: "a rat, medium-sized rodent belonging to the genus Rattus, or of certain other genera in the family Muridae", article: "de", plural: "ratten", forms: ["ratten"], source: "wiktionary" },
  { lemma: "rechtstreeks", pos: "adj", en: "direct", source: "wiktionary" },
  { lemma: "regen", pos: "noun", en: "rain", article: "de", source: "wiktionary" },
  { lemma: "reis", pos: "noun", en: "travel", article: "de", source: "wiktionary" },
  { lemma: "retour", pos: "adv", en: "back whence one came", source: "wiktionary" },
  { lemma: "rijden", pos: "verb", en: "to ride", participle: "gereden", source: "wiktionary" },
  { lemma: "rijst", pos: "noun", en: "rice", article: "de", source: "wiktionary" },
  { lemma: "rood", pos: "adj", en: "red", source: "wiktionary" },
  { lemma: "roze", pos: "adj", en: "pink, rosy", source: "wiktionary" },
  { lemma: "rug", pos: "noun", en: "back, backside", article: "de", plural: "ruggen", forms: ["ruggen"], source: "wiktionary" },
  { lemma: "rustig", pos: "adj", en: "calm, tranquil, quiet", source: "wiktionary" },
  { lemma: "siemens", pos: "noun", en: "siemens (unit of electrical conductance)", article: "de", forms: ["s"], source: "wiktionary" },
  { lemma: "salade", pos: "noun", en: "salad (a food made primarily of a mixture of raw ingredients, typically vegetables)", article: "de", plural: "salades", forms: ["salades"], source: "wiktionary" },
  { lemma: "samen", pos: "adv", en: "together", source: "wiktionary" },
  { lemma: "sap", pos: "noun", en: "juice", article: "het", plural: "sappen", forms: ["sappen"], source: "wiktionary" },
  { lemma: "saus", pos: "noun", en: "sauce (liquid condiment, usually of more than watery consistency)", article: "de", forms: ["sauzen"], source: "wiktionary" },
  { lemma: "schaap", pos: "noun", en: "sheep (a woolly ruminant animal of the genus Ovis)", article: "het", plural: "schapen", forms: ["schapen"], source: "wiktionary" },
  { lemma: "schapen", pos: "verb", en: "alternative form of scheppen", participle: "geschapen", forms: ["schaap"], source: "wiktionary" },
  { lemma: "schijnen", pos: "verb", en: "to shine", participle: "geschenen", forms: ["schijnt"], source: "wiktionary" },
  { lemma: "school", pos: "noun", en: "a school, educational institution that provides education, whether combined with research or not", article: "de", source: "wiktionary" },
  { lemma: "schreef", pos: "noun", en: "line, stroke of the pen", plural: "schreven", forms: ["schreven"], source: "wiktionary" },
  { lemma: "sinaasappel", pos: "noun", en: "orange (fruit)", article: "de", forms: ["sinaasappels"], source: "wiktionary" },
  { lemma: "sla", pos: "noun", en: "lettuce", article: "de", source: "wiktionary" },
  { lemma: "slaapkamer", pos: "noun", en: "bedroom", article: "de", plural: "slaapkamers", forms: ["slaapkamers"], source: "wiktionary" },
  { lemma: "slecht", pos: "adj", en: "bad", source: "wiktionary" },
  { lemma: "sleutel", pos: "noun", en: "a key", article: "de", plural: "sleutels", forms: ["sleutels"], source: "wiktionary" },
  { lemma: "sneeuwen", pos: "verb", en: "to snow", participle: "gesneeuwd", forms: ["sneeuwt"], source: "wiktionary" },
  { lemma: "snel", pos: "adj", en: "fast, quick, rapid", source: "wiktionary" },
  { lemma: "soep", pos: "noun", en: "soup, liquid dish", article: "de", plural: "soepen", forms: ["soepen"], source: "wiktionary" },
  { lemma: "soms", pos: "adv", en: "sometimes", source: "wiktionary" },
  { lemma: "spel", pos: "noun", en: "game", article: "het", forms: ["spelen"], source: "wiktionary" },
  { lemma: "spin", pos: "noun", en: "spider (member of the order Araneae)", article: "de", plural: "spinnen", forms: ["spinnen"], source: "wiktionary" },
  { lemma: "spinnen", pos: "verb", en: "to spin: make yarn by twisting and winding fibres together", participle: "gesponnen", forms: ["spin"], source: "wiktionary" },
  { lemma: "spoor", pos: "noun", en: "track", article: "het", source: "wiktionary" },
  { lemma: "stoel", pos: "noun", en: "a chair, a piece of furniture used for sitting, normally portable and having four legs", article: "de", plural: "stoelen", forms: ["stoelen"], source: "wiktionary" },
  { lemma: "stoelen", pos: "verb", en: "To rest, be based/ founded, on something (such as an argumentation)", participle: "gestoeld", forms: ["stoel"], source: "wiktionary" },
  { lemma: "stond", pos: "noun", en: "time; point in time, moment", plural: "stonden", forms: ["stonden"], source: "wiktionary" },
  { lemma: "stoppen", pos: "verb", en: "to stop, to halt", participle: "gestopt", source: "wiktionary" },
  { lemma: "suiker", pos: "noun", en: "sugar", article: "de", source: "wiktionary" },
  { lemma: "taart", pos: "noun", en: "a pie, large cake, or cobbler", article: "de", plural: "taarten", forms: ["taarten"], source: "wiktionary" },
  { lemma: "tachtig", pos: "num", en: "eighty", source: "wiktionary" },
  { lemma: "tafel", pos: "noun", en: "table (item of furniture)", article: "de", plural: "tafels", forms: ["tafels"], source: "wiktionary" },
  { lemma: "tante", pos: "noun", en: "aunt (sister or sister-in-law of a parent)", article: "de", plural: "tantes", forms: ["tantes"], source: "wiktionary" },
  { lemma: "tasje", pos: "noun", en: "bag (diminutive)", article: "het", flags: ["diminutive"], source: "wiktionary" },
  { lemma: "thuis", pos: "adv", en: "at home (at one's dwelling or in one's home area)", source: "wiktionary" },
  { lemma: "tien", pos: "num", en: "ten", source: "wiktionary" },
  { lemma: "tomaat", pos: "noun", en: "tomato, fruit of Solanum lycopersicum", article: "de", plural: "tomaten", forms: ["tomaten"], source: "wiktionary" },
  { lemma: "tuin", pos: "noun", en: "a garden, yard", article: "de", plural: "tuinen", forms: ["tuinen"], source: "wiktionary" },
  { lemma: "tuinen", pos: "verb", en: "to practice agriculture or horticulture", participle: "getuind", forms: ["tuin"], source: "wiktionary" },
  { lemma: "twaalf", pos: "num", en: "twelve", source: "wiktionary" },
  { lemma: "tweeëndertig", pos: "num", en: "thirty-two", source: "wiktionary" },
  { lemma: "twintig", pos: "num", en: "twenty", source: "wiktionary" },
  { lemma: "ui", pos: "noun", en: "onion (Allium cepa)", article: "de", plural: "uien", forms: ["uien"], source: "wiktionary" },
  { lemma: "Utrecht", pos: "name", en: "Utrecht (a city and municipality, the capital of Utrecht province, Netherlands)", source: "wiktionary" },
  { lemma: "uur", pos: "noun", en: "an hour, a period of time", article: "het", source: "wiktionary" },
  { lemma: "vanavond", pos: "adv", en: "tonight, this evening, the evening of the current day (in the future or past)", source: "wiktionary" },
  { lemma: "vandaag", pos: "adv", en: "today", source: "wiktionary" },
  { lemma: "varken", pos: "noun", en: "pig (Sus scrofa domesticus)", article: "het", plural: "varkens", forms: ["varkens","beer"], source: "wiktionary" },
  { lemma: "veertien", pos: "num", en: "fourteen", source: "wiktionary" },
  { lemma: "veertig", pos: "num", en: "forty", source: "wiktionary" },
  { lemma: "vers", pos: "adj", en: "fresh", source: "wiktionary" },
  { lemma: "vertrekken", pos: "verb", en: "to depart, to leave", participle: "vertrokken", forms: ["vertrekt"], source: "wiktionary" },
  { lemma: "vierentwintig", pos: "num", en: "twenty-four", source: "wiktionary" },
  { lemma: "vijfenveertig", pos: "num", en: "forty-five", source: "wiktionary" },
  { lemma: "vijftien", pos: "num", en: "fifteen", source: "wiktionary" },
  { lemma: "vis", pos: "noun", en: "fish (aquatic organism)", article: "de", plural: "vissen", forms: ["vissen"], source: "wiktionary" },
  { lemma: "vissen", pos: "verb", en: "to fish, to try to catch fish", participle: "gevist", forms: ["vis"], source: "wiktionary" },
  { lemma: "vlees", pos: "noun", en: "meat", article: "het", source: "wiktionary" },
  { lemma: "vlinder", pos: "noun", en: "butterfly, or generally any insect belonging to the order Lepidoptera", article: "de", plural: "vlinders", forms: ["vlinders"], source: "wiktionary" },
  { lemma: "voet", pos: "noun", en: "foot (lowest part of the legs)", article: "de", plural: "voeten", forms: ["voeten"], source: "wiktionary" },
  { lemma: "Vogel", pos: "name", en: "a surname", source: "wiktionary" },
  { lemma: "Vogels", pos: "name", en: "a surname", source: "wiktionary" },
  { lemma: "vos", pos: "noun", en: "fox, carnivore of the tribe Vulpini", article: "de", plural: "vossen", forms: ["vossen"], source: "wiktionary" },
  { lemma: "vossen", pos: "verb", en: "to fuck", participle: "gevost", forms: ["vos"], source: "wiktionary" },
  { lemma: "vragen", pos: "verb", en: "to ask (a question)", participle: "gevraagd", forms: ["vroeg"], source: "wiktionary" },
  { lemma: "vriend", pos: "noun", en: "friend", article: "de", plural: "vrienden", forms: ["vrienden","vriendin"], source: "wiktionary" },
  { lemma: "vriendin", pos: "noun", en: "female friend", article: "de", plural: "vriendinnen", forms: ["vriendinnen","vriend"], source: "wiktionary" },
  { lemma: "vrijdag", pos: "noun", en: "Friday", article: "de", source: "wiktionary" },
  { lemma: "vroeg", pos: "adj", en: "early", forms: ["vroeger"], source: "wiktionary" },
  { lemma: "vroeger", pos: "adj", en: "having to do with or occurring in the past", source: "wiktionary" },
  { lemma: "vrouw", pos: "noun", en: "woman", article: "de", plural: "vrouwen", forms: ["vrouwen"], source: "wiktionary" },
  { lemma: "vrouwe", pos: "noun", en: "noblewoman", article: "de", plural: "vrouwen", forms: ["vrouwen"], source: "wiktionary" },
  { lemma: "waaien", pos: "verb", en: "to blow", participle: "gewaaid", forms: ["waait"], source: "wiktionary" },
  { lemma: "wanneer", pos: "adv", en: "when", source: "wiktionary" },
  { lemma: "weekend", pos: "noun", en: "weekend", article: "het", source: "wiktionary" },
  { lemma: "welk", pos: "det", en: "which, what", source: "wiktionary" },
  { lemma: "weten", pos: "verb", en: "to know (knowledge), to be aware of something", participle: "geweten", source: "wiktionary" },
  { lemma: "wit", pos: "adj", en: "white", source: "wiktionary" },
  { lemma: "woensdag", pos: "noun", en: "Wednesday", article: "de", source: "wiktionary" },
  { lemma: "wolf", pos: "noun", en: "wolf (Canis lupus; the largest wild member of the canine subfamily)", article: "de", plural: "wolven", forms: ["wolven"], source: "wiktionary" },
  { lemma: "woonkamer", pos: "noun", en: "living room", article: "de", plural: "woonkamers", forms: ["woonkamers"], source: "wiktionary" },
  { lemma: "wortel", pos: "noun", en: "root (especially of a plant)", article: "de", plural: "wortels", forms: ["wortels"], source: "wiktionary" },
  { lemma: "zaterdag", pos: "noun", en: "Saturday", article: "de", forms: ["zaterdag"], source: "wiktionary" },
  { lemma: "zes", pos: "num", en: "six", source: "wiktionary" },
  { lemma: "zestig", pos: "num", en: "sixty", source: "wiktionary" },
  { lemma: "zeven", pos: "num", en: "seven", source: "wiktionary" },
  { lemma: "zevenendertig", pos: "num", en: "thirty-seven", source: "wiktionary" },
  { lemma: "zeventig", pos: "num", en: "seventy", source: "wiktionary" },
  { lemma: "ziek", pos: "adj", en: "sick, ill", source: "wiktionary" },
  { lemma: "zin", pos: "noun", en: "meaning, significance", article: "de", source: "wiktionary" },
  { lemma: "zit", pos: "noun", en: "the act of sitting", article: "de", source: "wiktionary" },
  { lemma: "zo", pos: "adv", en: "so, thus, like that/this", source: "wiktionary" },
  { lemma: "zon", pos: "noun", en: "sun, Sun", article: "de", source: "wiktionary" },
  { lemma: "zondag", pos: "noun", en: "Sunday", article: "de", forms: ["zondag"], source: "wiktionary" },
  { lemma: "zoon", pos: "noun", en: "son", article: "de", forms: ["zonen"], source: "wiktionary" },
  { lemma: "zout", pos: "noun", en: "salt", article: "het", source: "wiktionary" },
  { lemma: "zus", pos: "noun", en: "sister", article: "de", plural: "zussen", forms: ["zussen"], source: "wiktionary" },
  { lemma: "zwart", pos: "adj", en: "black", source: "wiktionary" },
  { lemma: "zwemmen", pos: "verb", en: "to swim", participle: "gezwommen", source: "wiktionary" },
  { lemma: "één", pos: "num", en: "alternative form of een (“one”)", source: "wiktionary" },
];
