import type { SoundDrill } from "@/lib/types";

/** The sounds that make Dutch hard for English speakers, in the order worth learning them. */
export const soundDrills: SoundDrill[] = [
  {
    id: "g",
    symbol: "g / ch",
    name: "The scraped g",
    how: "Start to say 'k', then instead of stopping the air, let it keep scraping through. It's friction at the back of the throat, like clearing it gently. In the south and in Belgium it's softer; in Amsterdam it's harsh.",
    trap: "English speakers say a hard 'g' as in 'go'. Dutch has no such sound — it's always friction, never a clean stop.",
    words: [
      { target: "goed", en: "good" },
      { target: "graag", en: "gladly" },
      { target: "gaan", en: "to go" },
      { target: "acht", en: "eight" },
      { target: "lachen", en: "to laugh" },
      { target: "gezellig", en: "cosy / convivial" },
    ],
    tongueTwister: "Gezellig groen gras groeit goed.",
  },
  {
    id: "ui",
    symbol: "ui",
    name: "The impossible ui",
    how: "Round your lips as if for 'oo', start the sound, then slide your tongue forward and spread your lips toward 'i' — all in one motion. It's a glide, not a single vowel.",
    trap: "Saying it as 'ow' (like 'house') or as 'oy'. Neither is close. The lip movement is what makes it.",
    words: [
      { target: "huis", en: "house" },
      { target: "uit", en: "out" },
      { target: "buiten", en: "outside" },
      { target: "duim", en: "thumb" },
      { target: "vuil", en: "dirty" },
    ],
    tongueTwister: "Het vuile huis staat buiten.",
  },
  {
    id: "eu",
    symbol: "eu",
    name: "The rounded eu",
    how: "Say the 'u' of English 'hurt', then round your lips tightly while holding the sound. Close to French 'deux'.",
    trap: "Flattening it into 'oo' or into English 'you'. The lips stay rounded and the tongue stays forward.",
    words: [
      { target: "leuk", en: "nice / fun" },
      { target: "deur", en: "door" },
      { target: "kleur", en: "colour" },
      { target: "neus", en: "nose" },
      { target: "keuken", en: "kitchen" },
    ],
    tongueTwister: "De deur van de keuken heeft een leuke kleur.",
  },
  {
    id: "ij",
    symbol: "ij / ei",
    name: "The two spellings, one sound",
    how: "Somewhere between English 'eye' and 'ay'. Start lower in the mouth than 'ay' and glide up. 'ij' and 'ei' sound identical — only the spelling differs.",
    trap: "Pronouncing it as a long 'ee'. 'Wij' is not 'wee'.",
    words: [
      { target: "wij", en: "we" },
      { target: "tijd", en: "time" },
      { target: "trein", en: "train" },
      { target: "klein", en: "small" },
      { target: "blijven", en: "to stay" },
    ],
    tongueTwister: "Wij blijven een klein tijdje in de trein.",
  },
  {
    id: "ee",
    symbol: "ee",
    name: "The ee that isn't English ee",
    how: "A long, steady 'ay' — the vowel of English 'gate', but held flatter and without letting it slide toward 'ee' at the end. Keep your tongue still for the whole vowel.",
    trap: "Reading it with English eyes. In English 'ee' spells the sound in 'see'; in Dutch that sound is spelled 'ie'. So 'nee' is not 'knee', and 'zee' is not 'see' — they rhyme with 'say'. Getting this backwards makes ordinary words unrecognisable.",
    words: [
      { target: "nee", en: "no" },
      { target: "twee", en: "two" },
      { target: "thee", en: "tea" },
      { target: "veel", en: "much / many" },
      { target: "geen", en: "none / not a" },
      { target: "weer", en: "weather / again" },
    ],
    tongueTwister: "Twee mensen drinken thee aan de zee.",
  },
  {
    id: "ee-ie",
    symbol: "ee ↔ ie",
    name: "Telling ee and ie apart",
    how: "Say them back to back: 'zee' then 'zie'. For 'ee' the jaw is a little lower and the sound is 'ay'; for 'ie' the tongue is high and tight and it's the English 'ee' of 'see'.",
    trap: "Collapsing both into one vowel. These are separate words: 'veel' (much) and 'viel' (fell), 'meer' (more) and 'mier' (ant). Dutch listeners hear the difference immediately.",
    words: [
      { target: "zee", en: "sea" },
      { target: "zie", en: "(I) see" },
      { target: "veel", en: "much" },
      { target: "viel", en: "fell" },
      { target: "meer", en: "more" },
      { target: "mier", en: "ant" },
    ],
    tongueTwister: "Ik zie meer dan een mier bij de zee.",
  },
  {
    id: "w-v",
    symbol: "w / v",
    name: "The soft w",
    how: "Dutch 'w' is made with the bottom lip near the top teeth — lighter than an English 'v', firmer than an English 'w'. Dutch 'v' sits close to an English 'f' in many regions.",
    trap: "Using a full English 'w' (lips rounded, no teeth). 'Water' should not sound like the English word.",
    words: [
      { target: "water", en: "water" },
      { target: "wonen", en: "to live" },
      { target: "waarom", en: "why" },
      { target: "vader", en: "father" },
      { target: "vier", en: "four" },
    ],
    tongueTwister: "Waarom woont vader vier weken bij het water?",
  },
  {
    id: "oe-u",
    symbol: "oe / u",
    name: "oe versus u",
    how: "'oe' is a plain 'oo' as in English 'food'. Dutch 'u' is the tight rounded vowel — say 'ee' and then round your lips without moving your tongue.",
    trap: "Collapsing both into 'oo'. 'Buur' (neighbour) and 'boer' (farmer) are different words.",
    words: [
      { target: "boek", en: "book" },
      { target: "goed", en: "good" },
      { target: "vuur", en: "fire" },
      { target: "minuut", en: "minute" },
      { target: "buur", en: "neighbour" },
    ],
    tongueTwister: "De buurman leest een goed boek bij het vuur.",
  },
];
