import type { VerbEntry } from "@/lib/types";

/**
 * The verb-conjugation library — present, imperfectum, perfectum and future
 * for the verbs that carry most of everyday Dutch.
 *
 * Distinct from the "werkwoorden" vocabulary set (which just teaches meaning)
 * and from the sentence-builder verbs (which only need the present tense).
 * This is what a learner opens by tapping a verb directly, to see its whole
 * system rather than one form at a time.
 *
 * A mix of regular and irregular on purpose: regular ones show that the
 * 't kofschip rule is mechanical and learnable; irregular ones are simply
 * memorised, and are flagged as such via `note`.
 */
export const verbs: VerbEntry[] = [
  // ── The two you cannot avoid ────────────────────────────────────────────
  {
    id: "zijn",
    infinitive: "zijn",
    en: "to be",
    level: "A1",
    stem: "ben",
    irregular: { jij: "bent", hij: "is", wij: "zijn", jullie: "zijn", zij: "zijn" },
    auxiliary: "zijn",
    participle: "geweest",
    irregularPast: { singular: "was", plural: "waren" },
    note: "Irregular in every tense. There is no way around memorising this one first.",
    examples: {
      present: { target: "Ik ben moe.", en: "I am tired." },
      imperfectum: { target: "Ik was gisteren ziek.", en: "I was sick yesterday." },
      perfectum: { target: "Ik ben nog nooit in Parijs geweest.", en: "I've never been to Paris." },
      future: { target: "Morgen zal ik thuis zijn.", en: "Tomorrow I'll be at home." },
    },
  },
  {
    id: "hebben",
    infinitive: "hebben",
    en: "to have",
    level: "A1",
    stem: "heb",
    irregular: { hij: "heeft" },
    auxiliary: "hebben",
    participle: "gehad",
    irregularPast: { singular: "had", plural: "hadden" },
    note: "This is also the auxiliary most other verbs use to build their perfectum — learn it early and it pays twice.",
    examples: {
      present: { target: "Ik heb een broer.", en: "I have a brother." },
      imperfectum: { target: "Ik had geen tijd.", en: "I didn't have time." },
      perfectum: { target: "Wij hebben geluk gehad.", en: "We've been lucky." },
      future: { target: "Jullie zullen honger hebben.", en: "You'll be hungry." },
    },
  },

  // ── Motion ────────────────────────────────────────────────────────────────
  {
    id: "gaan",
    infinitive: "gaan",
    en: "to go",
    level: "A1",
    stem: "ga",
    irregular: { jij: "gaat", hij: "gaat" },
    auxiliary: "zijn",
    participle: "gegaan",
    irregularPast: { singular: "ging", plural: "gingen" },
    note: "The present tense doesn't just add -t to the stem — 'gaat' is the whole word, not 'gat'. 'Staan' and 'slaan' work the same way.",
    examples: {
      present: { target: "Ik ga naar school.", en: "I go to school." },
      imperfectum: { target: "Ik ging vroeg naar bed.", en: "I went to bed early." },
      perfectum: { target: "Zij is naar huis gegaan.", en: "She has gone home." },
      future: { target: "Wij zullen morgen gaan.", en: "We'll go tomorrow." },
    },
  },
  {
    id: "komen",
    infinitive: "komen",
    en: "to come",
    level: "A1",
    stem: "kom",
    auxiliary: "zijn",
    participle: "gekomen",
    irregularPast: { singular: "kwam", plural: "kwamen" },
    examples: {
      present: { target: "Hij komt morgen.", en: "He's coming tomorrow." },
      imperfectum: { target: "Zij kwam te laat.", en: "She came too late." },
      perfectum: { target: "Ik ben net gekomen.", en: "I've just arrived." },
      future: { target: "Jij zult zeker komen.", en: "You'll definitely come." },
    },
  },
  {
    id: "lopen",
    infinitive: "lopen",
    en: "to walk",
    level: "A1",
    stem: "loop",
    auxiliary: "hebben",
    participle: "gelopen",
    irregularPast: { singular: "liep", plural: "liepen" },
    examples: {
      present: { target: "Ik loop naar het station.", en: "I walk to the station." },
      imperfectum: { target: "Wij liepen door het park.", en: "We walked through the park." },
      perfectum: { target: "Hij heeft de hele dag gelopen.", en: "He's been walking all day." },
      future: { target: "Ik zal langzamer lopen.", en: "I'll walk more slowly." },
    },
  },
  {
    id: "staan",
    infinitive: "staan",
    en: "to stand",
    level: "A1",
    stem: "sta",
    irregular: { jij: "staat", hij: "staat" },
    auxiliary: "hebben",
    participle: "gestaan",
    irregularPast: { singular: "stond", plural: "stonden" },
    examples: {
      present: { target: "De auto staat buiten.", en: "The car is outside." },
      imperfectum: { target: "Ik stond op het perron.", en: "I was standing on the platform." },
      perfectum: { target: "Wij hebben een uur gestaan.", en: "We stood for an hour." },
      future: { target: "Het zal daar nog staan.", en: "It'll still be standing there." },
    },
  },

  // ── Daily actions ─────────────────────────────────────────────────────────
  {
    id: "doen",
    infinitive: "doen",
    en: "to do",
    level: "A1",
    stem: "doe",
    auxiliary: "hebben",
    participle: "gedaan",
    irregularPast: { singular: "deed", plural: "deden" },
    examples: {
      present: { target: "Wat doe jij vandaag?", en: "What are you doing today?" },
      imperfectum: { target: "Ik deed boodschappen.", en: "I was doing the shopping." },
      perfectum: { target: "Zij heeft haar best gedaan.", en: "She's done her best." },
      future: { target: "Ik zal het morgen doen.", en: "I'll do it tomorrow." },
    },
  },
  {
    id: "eten",
    infinitive: "eten",
    en: "to eat",
    level: "A1",
    stem: "eet",
    auxiliary: "hebben",
    participle: "gegeten",
    irregularPast: { singular: "at", plural: "aten" },
    examples: {
      present: { target: "Wij eten om zes uur.", en: "We eat at six." },
      imperfectum: { target: "Ik at brood met kaas.", en: "I ate bread with cheese." },
      perfectum: { target: "Heb je al gegeten?", en: "Have you eaten yet?" },
      future: { target: "Wij zullen buiten eten.", en: "We'll eat outside." },
    },
  },
  {
    id: "drinken",
    infinitive: "drinken",
    en: "to drink",
    level: "A1",
    stem: "drink",
    auxiliary: "hebben",
    participle: "gedronken",
    irregularPast: { singular: "dronk", plural: "dronken" },
    examples: {
      present: { target: "Ik drink elke ochtend koffie.", en: "I drink coffee every morning." },
      imperfectum: { target: "Wij dronken thee bij oma.", en: "We drank tea at grandma's." },
      perfectum: { target: "Hij heeft te veel gedronken.", en: "He's drunk too much." },
      future: { target: "Ik zal water drinken.", en: "I'll drink water." },
    },
  },
  {
    id: "slapen",
    infinitive: "slapen",
    en: "to sleep",
    level: "A1",
    stem: "slaap",
    auxiliary: "hebben",
    participle: "geslapen",
    irregularPast: { singular: "sliep", plural: "sliepen" },
    examples: {
      present: { target: "Het kind slaapt al.", en: "The child is already asleep." },
      imperfectum: { target: "Ik sliep slecht.", en: "I slept badly." },
      perfectum: { target: "Wij hebben acht uur geslapen.", en: "We slept eight hours." },
      future: { target: "Jullie zullen goed slapen.", en: "You'll sleep well." },
    },
  },
  {
    id: "kopen",
    infinitive: "kopen",
    en: "to buy",
    level: "A1",
    stem: "koop",
    auxiliary: "hebben",
    participle: "gekocht",
    irregularPast: { singular: "kocht", plural: "kochten" },
    note: "The past tense is 'kocht', not 'koopte' — one of the small group of verbs the kofschip rule doesn't predict.",
    examples: {
      present: { target: "Ik koop een nieuwe jas.", en: "I'm buying a new coat." },
      imperfectum: { target: "Zij kocht een cadeau.", en: "She bought a gift." },
      perfectum: { target: "Wij hebben een huis gekocht.", en: "We've bought a house." },
      future: { target: "Ik zal het morgen kopen.", en: "I'll buy it tomorrow." },
    },
  },
  {
    id: "betalen",
    infinitive: "betalen",
    en: "to pay",
    level: "A1",
    stem: "betaal",
    auxiliary: "hebben",
    participle: "betaald",
    note: "Starts with 'be-', so the participle has no 'ge-' prefix — 'betaald', never 'gebetaald'.",
    examples: {
      present: { target: "Ik betaal met kaart.", en: "I pay by card." },
      imperfectum: { target: "Hij betaalde contant.", en: "He paid cash." },
      perfectum: { target: "Heb je al betaald?", en: "Have you already paid?" },
      future: { target: "Wij zullen samen betalen.", en: "We'll pay together." },
    },
  },
  {
    id: "geven",
    infinitive: "geven",
    en: "to give",
    level: "A1",
    stem: "geef",
    auxiliary: "hebben",
    participle: "gegeven",
    irregularPast: { singular: "gaf", plural: "gaven" },
    examples: {
      present: { target: "Ik geef je mijn nummer.", en: "I'll give you my number." },
      imperfectum: { target: "Zij gaf hem een boek.", en: "She gave him a book." },
      perfectum: { target: "Wij hebben veel geld gegeven.", en: "We've given a lot of money." },
      future: { target: "Ik zal het je geven.", en: "I'll give it to you." },
    },
  },
  {
    id: "nemen",
    infinitive: "nemen",
    en: "to take",
    level: "A1",
    stem: "neem",
    auxiliary: "hebben",
    participle: "genomen",
    irregularPast: { singular: "nam", plural: "namen" },
    examples: {
      present: { target: "Ik neem de trein.", en: "I take the train." },
      imperfectum: { target: "Hij nam een grote hap.", en: "He took a big bite." },
      perfectum: { target: "Wij hebben een pauze genomen.", en: "We've taken a break." },
      future: { target: "Ik zal de bus nemen.", en: "I'll take the bus." },
    },
  },
  {
    id: "zien",
    infinitive: "zien",
    en: "to see",
    level: "A1",
    stem: "zie",
    auxiliary: "hebben",
    participle: "gezien",
    irregularPast: { singular: "zag", plural: "zagen" },
    examples: {
      present: { target: "Ik zie een vogel.", en: "I see a bird." },
      imperfectum: { target: "Wij zagen de zon ondergaan.", en: "We saw the sun go down." },
      perfectum: { target: "Heb je die film gezien?", en: "Have you seen that film?" },
      future: { target: "Ik zal je morgen zien.", en: "I'll see you tomorrow." },
    },
  },
  {
    id: "lezen",
    infinitive: "lezen",
    en: "to read",
    level: "A1",
    stem: "lees",
    auxiliary: "hebben",
    participle: "gelezen",
    irregularPast: { singular: "las", plural: "lazen" },
    examples: {
      present: { target: "Ik lees een boek.", en: "I'm reading a book." },
      imperfectum: { target: "Zij las de krant.", en: "She read the newspaper." },
      perfectum: { target: "Wij hebben het al gelezen.", en: "We've already read it." },
      future: { target: "Ik zal het vanavond lezen.", en: "I'll read it tonight." },
    },
  },
  {
    id: "schrijven",
    infinitive: "schrijven",
    en: "to write",
    level: "A1",
    stem: "schrijf",
    auxiliary: "hebben",
    participle: "geschreven",
    irregularPast: { singular: "schreef", plural: "schreven" },
    examples: {
      present: { target: "Ik schrijf een e-mail.", en: "I'm writing an email." },
      imperfectum: { target: "Hij schreef een brief.", en: "He wrote a letter." },
      perfectum: { target: "Wij hebben een kaart geschreven.", en: "We've written a card." },
      future: { target: "Ik zal je snel schrijven.", en: "I'll write to you soon." },
    },
  },
  {
    id: "vinden",
    infinitive: "vinden",
    en: "to find / to think of",
    level: "A1",
    stem: "vind",
    auxiliary: "hebben",
    participle: "gevonden",
    irregularPast: { singular: "vond", plural: "vonden" },
    note: "Also the everyday word for opinions: 'Ik vind het leuk' — I think it's nice.",
    examples: {
      present: { target: "Ik vind dit leuk.", en: "I like this." },
      imperfectum: { target: "Wij vonden het huis snel.", en: "We found the house quickly." },
      perfectum: { target: "Heb je je sleutels gevonden?", en: "Have you found your keys?" },
      future: { target: "Ik zal een oplossing vinden.", en: "I'll find a solution." },
    },
  },
  {
    id: "beginnen",
    infinitive: "beginnen",
    en: "to begin",
    level: "A1",
    stem: "begin",
    auxiliary: "zijn",
    participle: "begonnen",
    irregularPast: { singular: "begon", plural: "begonnen" },
    note: "Starts with 'be-', so no 'ge-' on the participle — it's 'begonnen', not 'gebegonnen'.",
    examples: {
      present: { target: "De les begint om negen uur.", en: "The lesson starts at nine." },
      imperfectum: { target: "Het begon te regenen.", en: "It started to rain." },
      perfectum: { target: "Wij zijn net begonnen.", en: "We've just started." },
      future: { target: "De film zal zo beginnen.", en: "The film will start soon." },
    },
  },

  // ── Regular verbs — the 't kofschip rule in action ──────────────────────
  {
    id: "werken",
    infinitive: "werken",
    en: "to work",
    level: "A1",
    stem: "werk",
    auxiliary: "hebben",
    participle: "gewerkt",
    note: "Regular. Stem ends in 'k' — a kofschip letter — so the past takes -te/-ten.",
    examples: {
      present: { target: "Ik werk in Utrecht.", en: "I work in Utrecht." },
      imperfectum: { target: "Ik werkte gisteren tot laat.", en: "I worked late yesterday." },
      perfectum: { target: "Wij hebben hard gewerkt.", en: "We've worked hard." },
      future: { target: "Ik zal morgen thuis werken.", en: "I'll work from home tomorrow." },
    },
  },
  {
    id: "wonen",
    infinitive: "wonen",
    en: "to live / to reside",
    level: "A1",
    stem: "woon",
    auxiliary: "hebben",
    participle: "gewoond",
    note: "Regular. Stem ends in 'n' — not a kofschip letter — so the past takes -de/-den.",
    examples: {
      present: { target: "Ik woon in Amsterdam.", en: "I live in Amsterdam." },
      imperfectum: { target: "Vroeger woonde ik in Rotterdam.", en: "I used to live in Rotterdam." },
      perfectum: { target: "Wij hebben hier lang gewoond.", en: "We've lived here a long time." },
      future: { target: "Zij zullen in Den Haag wonen.", en: "They'll live in The Hague." },
    },
  },
  {
    id: "maken",
    infinitive: "maken",
    en: "to make",
    level: "A1",
    stem: "maak",
    auxiliary: "hebben",
    participle: "gemaakt",
    examples: {
      present: { target: "Ik maak het eten.", en: "I'm making dinner." },
      imperfectum: { target: "Wij maakten veel foto's.", en: "We took lots of photos." },
      perfectum: { target: "Heb je je huiswerk gemaakt?", en: "Have you done your homework?" },
      future: { target: "Ik zal het snel maken.", en: "I'll make it soon." },
    },
  },
  {
    id: "spelen",
    infinitive: "spelen",
    en: "to play",
    level: "A1",
    stem: "speel",
    auxiliary: "hebben",
    participle: "gespeeld",
    examples: {
      present: { target: "De kinderen spelen buiten.", en: "The children are playing outside." },
      imperfectum: { target: "Wij speelden een spel.", en: "We played a game." },
      perfectum: { target: "Hij heeft goed gespeeld.", en: "He's played well." },
      future: { target: "Zij zullen morgen spelen.", en: "They'll play tomorrow." },
    },
  },
  {
    id: "leren",
    infinitive: "leren",
    en: "to learn / to teach",
    level: "A1",
    stem: "leer",
    auxiliary: "hebben",
    participle: "geleerd",
    examples: {
      present: { target: "Ik leer Nederlands.", en: "I'm learning Dutch." },
      imperfectum: { target: "Ik leerde snel.", en: "I learned quickly." },
      perfectum: { target: "Wij hebben veel geleerd.", en: "We've learned a lot." },
      future: { target: "Ik zal het je leren.", en: "I'll teach you." },
    },
  },
  {
    id: "praten",
    infinitive: "praten",
    en: "to talk",
    level: "A1",
    stem: "praat",
    auxiliary: "hebben",
    participle: "gepraat",
    note: "Stem already ends in 't', so no doubling anywhere: ik/jij/hij all say 'praat'.",
    examples: {
      present: { target: "Wij praten Nederlands.", en: "We speak Dutch (to each other)." },
      imperfectum: { target: "Ik praatte met de buren.", en: "I talked with the neighbours." },
      perfectum: { target: "Hebben jullie erover gepraat?", en: "Have you talked about it?" },
      future: { target: "Ik zal er rustig over praten.", en: "I'll talk about it calmly." },
    },
  },
  {
    id: "luisteren",
    infinitive: "luisteren",
    en: "to listen",
    level: "A1",
    stem: "luister",
    auxiliary: "hebben",
    participle: "geluisterd",
    examples: {
      present: { target: "Ik luister naar muziek.", en: "I'm listening to music." },
      imperfectum: { target: "Wij luisterden naar de radio.", en: "We listened to the radio." },
      perfectum: { target: "Heb je goed geluisterd?", en: "Have you listened carefully?" },
      future: { target: "Ik zal beter luisteren.", en: "I'll listen better." },
    },
  },
  {
    id: "koken",
    infinitive: "koken",
    en: "to cook",
    level: "A1",
    stem: "kook",
    auxiliary: "hebben",
    participle: "gekookt",
    examples: {
      present: { target: "Ik kook vanavond.", en: "I'm cooking tonight." },
      imperfectum: { target: "Mijn vader kookte elke dag.", en: "My father cooked every day." },
      perfectum: { target: "Wij hebben pasta gekookt.", en: "We've cooked pasta." },
      future: { target: "Ik zal iets lekkers koken.", en: "I'll cook something nice." },
    },
  },
  {
    id: "fietsen",
    infinitive: "fietsen",
    en: "to cycle",
    level: "A1",
    stem: "fiets",
    auxiliary: "hebben",
    participle: "gefietst",
    examples: {
      present: { target: "Ik fiets naar mijn werk.", en: "I cycle to work." },
      imperfectum: { target: "Wij fietsten door de regen.", en: "We cycled through the rain." },
      perfectum: { target: "Zij heeft dertig kilometer gefietst.", en: "She's cycled thirty kilometres." },
      future: { target: "Ik zal morgen fietsen.", en: "I'll cycle tomorrow." },
    },
  },
];
