import type { VocabSet } from "@/lib/types";

/**
 * Themed word sets.
 *
 * Lessons teach phrases you can say; these teach the words you slot into them.
 * Nouns always carry their article, because "boek" on its own is only half the
 * word — you have to learn "het boek" as a single unit or you will guess wrong
 * forever.
 */
export const vocabSets: VocabSet[] = [
  {
    id: "getallen-1-10",
    title: "Eén tot tien",
    titleEn: "One to ten",
    level: "A1",
    icon: "🔢",
    blurb: "The first ten. Everything else in Dutch counting is built from these.",
    items: [
      { target: "één", en: "one", icon: "1️⃣", say: "ayn" },
      { target: "twee", en: "two", icon: "2️⃣", say: "tvay" },
      { target: "drie", en: "three", icon: "3️⃣", say: "dree" },
      { target: "vier", en: "four", icon: "4️⃣", say: "veer" },
      { target: "vijf", en: "five", icon: "5️⃣", say: "vayf" },
      { target: "zes", en: "six", icon: "6️⃣", say: "zes" },
      { target: "zeven", en: "seven", icon: "7️⃣", say: "ZAY-vun" },
      { target: "acht", en: "eight", icon: "8️⃣", say: "akht" },
      { target: "negen", en: "nine", icon: "9️⃣", say: "NAY-ghun" },
      { target: "tien", en: "ten", icon: "🔟", say: "teen" },
    ],
    examples: [
      { target: "Ik heb twee broers.", en: "I have two brothers." },
      { target: "Vijf broden, alstublieft.", en: "Five loaves, please." },
      { target: "Het is drie uur.", en: "It's three o'clock." },
    ],
  },
  {
    id: "getallen-11-100",
    title: "Elf tot honderd",
    titleEn: "Eleven to a hundred",
    level: "A1",
    icon: "💯",
    blurb: "The tens, and the backwards habit: Dutch says the unit before the ten.",
    items: [
      { target: "elf", en: "eleven", say: "elf" },
      { target: "twaalf", en: "twelve", say: "TVAALF" },
      { target: "dertien", en: "thirteen", say: "DER-teen" },
      { target: "veertien", en: "fourteen", say: "VAYR-teen" },
      { target: "vijftien", en: "fifteen", say: "VAYF-teen" },
      { target: "twintig", en: "twenty", say: "TVIN-tukh" },
      { target: "dertig", en: "thirty", say: "DER-tukh" },
      { target: "veertig", en: "forty", say: "VAYR-tukh" },
      { target: "vijftig", en: "fifty", say: "VAYF-tukh" },
      { target: "zestig", en: "sixty", say: "ZES-tukh" },
      { target: "zeventig", en: "seventy", say: "ZAY-vun-tukh" },
      { target: "tachtig", en: "eighty", say: "TAKH-tukh" },
      { target: "negentig", en: "ninety", say: "NAY-ghun-tukh" },
      { target: "honderd", en: "a hundred", say: "HON-dert" },
    ],
    examples: [
      { target: "eenentwintig", en: "twenty-one — literally one-and-twenty" },
      { target: "vijfenveertig", en: "forty-five — five-and-forty" },
      { target: "Dat is negenennegentig euro.", en: "That's ninety-nine euros." },
    ],
  },
  {
    id: "familie",
    title: "De familie",
    titleEn: "Family",
    level: "A1",
    icon: "👨‍👩‍👧",
    blurb: "People you'll mention constantly. Note that almost all of them are de-words.",
    items: [
      { target: "vader", article: "de", plural: "vaders", en: "father", icon: "👨" },
      { target: "moeder", article: "de", plural: "moeders", en: "mother", icon: "👩" },
      { target: "ouders", article: "de", en: "parents", icon: "👫" },
      { target: "broer", article: "de", plural: "broers", en: "brother", icon: "👦" },
      { target: "zus", article: "de", plural: "zussen", en: "sister", icon: "👧" },
      { target: "zoon", article: "de", plural: "zonen", en: "son" },
      { target: "dochter", article: "de", plural: "dochters", en: "daughter" },
      { target: "kind", article: "het", plural: "kinderen", en: "child", icon: "🧒" },
      { target: "man", article: "de", plural: "mannen", en: "man / husband" },
      { target: "vrouw", article: "de", plural: "vrouwen", en: "woman / wife" },
      { target: "meneer", article: "de", en: "sir / Mr" },
      { target: "mevrouw", article: "de", en: "madam / Mrs" },
      { target: "opa", article: "de", plural: "opa's", en: "grandad", icon: "👴" },
      { target: "oma", article: "de", plural: "oma's", en: "grandma", icon: "👵" },
      { target: "oom", article: "de", plural: "ooms", en: "uncle" },
      { target: "tante", article: "de", plural: "tantes", en: "aunt" },
      { target: "vriend", article: "de", plural: "vrienden", en: "friend / boyfriend" },
      { target: "vriendin", article: "de", plural: "vriendinnen", en: "friend (f) / girlfriend" },
    ],
    examples: [
      { target: "Dit is mijn moeder.", en: "This is my mother." },
      { target: "Mijn ouders wonen in Engeland.", en: "My parents live in England." },
      { target: "Het kind speelt buiten.", en: "The child is playing outside." },
    ],
  },
  {
    id: "kleuren",
    title: "De kleuren",
    titleEn: "Colours",
    level: "A1",
    icon: "🎨",
    blurb: "Adjectives you can drop into almost any sentence to say more with less.",
    items: [
      { target: "rood", en: "red", icon: "🔴" },
      { target: "blauw", en: "blue", icon: "🔵" },
      { target: "groen", en: "green", icon: "🟢" },
      { target: "geel", en: "yellow", icon: "🟡" },
      { target: "zwart", en: "black", icon: "⚫" },
      { target: "wit", en: "white", icon: "⚪" },
      { target: "oranje", en: "orange", icon: "🟠" },
      { target: "paars", en: "purple", icon: "🟣" },
      { target: "bruin", en: "brown", icon: "🟤" },
      { target: "grijs", en: "grey" },
      { target: "roze", en: "pink" },
    ],
    examples: [
      { target: "De auto is rood.", en: "The car is red." },
      { target: "Ik zoek een blauwe jas.", en: "I'm looking for a blue coat." },
      { target: "Oranje is de kleur van Nederland.", en: "Orange is the colour of the Netherlands." },
    ],
  },
  {
    id: "eten-woorden",
    title: "Eten en drinken",
    titleEn: "Food and drink",
    level: "A1",
    icon: "🍞",
    blurb: "Supermarket and menu basics. Watch the articles — they're split fairly evenly here.",
    items: [
      { target: "brood", article: "het", plural: "broden", en: "bread", icon: "🍞" },
      { target: "boterham", article: "de", plural: "boterhammen", en: "sandwich slice", icon: "🥪" },
      { target: "kaas", article: "de", plural: "kazen", en: "cheese", icon: "🧀" },
      { target: "boter", article: "de", en: "butter", icon: "🧈" },
      { target: "vlees", article: "het", en: "meat", icon: "🥩" },
      { target: "kip", article: "de", plural: "kippen", en: "chicken (meat)", icon: "🍗" },
      { target: "vis", article: "de", plural: "vissen", en: "fish", icon: "🐟" },
      { target: "ei", article: "het", plural: "eieren", en: "egg", icon: "🥚" },
      { target: "rijst", article: "de", en: "rice", icon: "🍚" },
      { target: "pasta", article: "de", en: "pasta", icon: "🍝" },
      { target: "soep", article: "de", plural: "soepen", en: "soup", icon: "🍲" },
      { target: "salade", article: "de", plural: "salades", en: "salad", icon: "🥗" },
      { target: "saus", article: "de", plural: "sauzen", en: "sauce", icon: "🫙" },
      { target: "taart", article: "de", plural: "taarten", en: "cake", icon: "🍰" },
      { target: "koek", article: "de", plural: "koeken", en: "biscuit / cake", icon: "🍪" },
      { target: "chocolade", article: "de", en: "chocolate", icon: "🍫" },
      { target: "ijs", article: "het", en: "ice cream / ice", icon: "🍦" },
      { target: "honing", article: "de", en: "honey", icon: "🍯" },
      { target: "suiker", article: "de", en: "sugar" },
      { target: "zout", article: "het", en: "salt" },
      { target: "peper", article: "de", en: "pepper (spice)" },
      { target: "olie", article: "de", en: "oil" },
      { target: "water", article: "het", en: "water", icon: "💧" },
      { target: "melk", article: "de", en: "milk", icon: "🥛" },
      { target: "sap", article: "het", plural: "sappen", en: "juice", icon: "🧃" },
      { target: "koffie", article: "de", en: "coffee", icon: "☕" },
      { target: "thee", article: "de", en: "tea", icon: "🍵" },
      { target: "frisdrank", article: "de", en: "soft drink", icon: "🥤" },
      { target: "bier", article: "het", plural: "bieren", en: "beer", icon: "🍺" },
      { target: "wijn", article: "de", plural: "wijnen", en: "wine", icon: "🍷" },
    ],
    examples: [
      { target: "Ik drink water.", en: "I drink water." },
      { target: "Een broodje kaas, graag.", en: "A cheese roll, please." },
      { target: "Zij eet geen vlees.", en: "She doesn't eat meat." },
      { target: "Mag ik een beetje suiker in mijn koffie?", en: "Could I have a little sugar in my coffee?" },
    ],
  },
  {
    id: "groente-fruit",
    title: "Groente en fruit",
    titleEn: "Fruit and vegetables",
    level: "A1",
    icon: "🍎",
    blurb: "The produce aisle. Most fruit and vegetable names are de-words — a rare bit of consistency.",
    items: [
      { target: "fruit", article: "het", en: "fruit (category)", icon: "🍏" },
      { target: "groente", article: "de", plural: "groenten", en: "vegetables (category)", icon: "🥦" },
      { target: "appel", article: "de", plural: "appels", en: "apple", icon: "🍎" },
      { target: "banaan", article: "de", plural: "bananen", en: "banana", icon: "🍌" },
      { target: "sinaasappel", article: "de", plural: "sinaasappels", en: "orange", icon: "🍊" },
      { target: "citroen", article: "de", plural: "citroenen", en: "lemon", icon: "🍋" },
      { target: "peer", article: "de", plural: "peren", en: "pear", icon: "🍐" },
      { target: "druif", article: "de", plural: "druiven", en: "grape", icon: "🍇" },
      { target: "aardbei", article: "de", plural: "aardbeien", en: "strawberry", icon: "🍓" },
      { target: "perzik", article: "de", plural: "perziken", en: "peach", icon: "🍑" },
      { target: "aardappel", article: "de", plural: "aardappels", en: "potato", icon: "🥔" },
      { target: "tomaat", article: "de", plural: "tomaten", en: "tomato", icon: "🍅" },
      { target: "wortel", article: "de", plural: "wortels", en: "carrot", icon: "🥕" },
      { target: "ui", article: "de", plural: "uien", en: "onion", icon: "🧅" },
      { target: "knoflook", article: "de", en: "garlic", icon: "🧄" },
      { target: "paprika", article: "de", plural: "paprika's", en: "bell pepper", icon: "🫑" },
      { target: "komkommer", article: "de", plural: "komkommers", en: "cucumber", icon: "🥒" },
      { target: "sla", article: "de", en: "lettuce", icon: "🥬" },
      { target: "champignon", article: "de", plural: "champignons", en: "mushroom", icon: "🍄" },
    ],
    examples: [
      { target: "Ik koop appels en bananen.", en: "I'm buying apples and bananas." },
      { target: "Deze tomaten zijn vers.", en: "These tomatoes are fresh." },
      { target: "Hij eet geen ui.", en: "He doesn't eat onion." },
    ],
  },
  {
    id: "dieren",
    title: "De dieren",
    titleEn: "Animals",
    level: "A1",
    icon: "🐄",
    blurb: "Easy wins, and useful far beyond the farm — half of them turn up in idioms.",
    items: [
      { target: "hond", article: "de", plural: "honden", en: "dog", icon: "🐕" },
      { target: "kat", article: "de", plural: "katten", en: "cat", icon: "🐈" },
      { target: "paard", article: "het", plural: "paarden", en: "horse", icon: "🐎" },
      { target: "koe", article: "de", plural: "koeien", en: "cow", icon: "🐄" },
      { target: "schaap", article: "het", plural: "schapen", en: "sheep", icon: "🐑" },
      { target: "varken", article: "het", plural: "varkens", en: "pig", icon: "🐖" },
      { target: "geit", article: "de", plural: "geiten", en: "goat", icon: "🐐" },
      { target: "kip", article: "de", plural: "kippen", en: "chicken", icon: "🐔" },
      { target: "haan", article: "de", plural: "hanen", en: "rooster", icon: "🐓" },
      { target: "eend", article: "de", plural: "eenden", en: "duck", icon: "🦆" },
      { target: "vogel", article: "de", plural: "vogels", en: "bird", icon: "🐦" },
      { target: "muis", article: "de", plural: "muizen", en: "mouse", icon: "🐁" },
      { target: "rat", article: "de", plural: "ratten", en: "rat", icon: "🐀" },
      { target: "konijn", article: "het", plural: "konijnen", en: "rabbit", icon: "🐇" },
      { target: "vis", article: "de", plural: "vissen", en: "fish", icon: "🐟" },
      { target: "leeuw", article: "de", plural: "leeuwen", en: "lion", icon: "🦁" },
      { target: "olifant", article: "de", plural: "olifanten", en: "elephant", icon: "🐘" },
      { target: "aap", article: "de", plural: "apen", en: "monkey", icon: "🐒" },
      { target: "beer", article: "de", plural: "beren", en: "bear", icon: "🐻" },
      { target: "vos", article: "de", plural: "vossen", en: "fox", icon: "🦊" },
      { target: "wolf", article: "de", plural: "wolven", en: "wolf", icon: "🐺" },
      { target: "vlinder", article: "de", plural: "vlinders", en: "butterfly", icon: "🦋" },
      { target: "spin", article: "de", plural: "spinnen", en: "spider", icon: "🕷️" },
      { target: "bij", article: "de", plural: "bijen", en: "bee", icon: "🐝" },
    ],
    examples: [
      { target: "De hond is groot.", en: "The dog is big." },
      { target: "Wij hebben een kat.", en: "We have a cat." },
      { target: "Het paard eet gras.", en: "The horse eats grass." },
      { target: "Er zit een spin op de muur.", en: "There's a spider on the wall." },
    ],
  },
  {
    id: "lichaam",
    title: "Het lichaam",
    titleEn: "The body",
    level: "A1",
    icon: "🖐️",
    blurb: "What you need at the doctor, and for saying what hurts.",
    items: [
      { target: "hoofd", article: "het", plural: "hoofden", en: "head" },
      { target: "haar", article: "het", en: "hair" },
      { target: "oog", article: "het", plural: "ogen", en: "eye", icon: "👁️" },
      { target: "oor", article: "het", plural: "oren", en: "ear", icon: "👂" },
      { target: "neus", article: "de", plural: "neuzen", en: "nose", icon: "👃" },
      { target: "mond", article: "de", plural: "monden", en: "mouth", icon: "👄" },
      { target: "hand", article: "de", plural: "handen", en: "hand", icon: "✋" },
      { target: "arm", article: "de", plural: "armen", en: "arm", icon: "💪" },
      { target: "been", article: "het", plural: "benen", en: "leg", icon: "🦵" },
      { target: "voet", article: "de", plural: "voeten", en: "foot", icon: "🦶" },
      { target: "buik", article: "de", plural: "buiken", en: "belly" },
      { target: "rug", article: "de", plural: "ruggen", en: "back" },
    ],
    examples: [
      { target: "Mijn hoofd doet pijn.", en: "My head hurts." },
      { target: "Zij heeft blauwe ogen.", en: "She has blue eyes." },
    ],
  },
  {
    id: "tijd-woorden",
    title: "Dagen en maanden",
    titleEn: "Days and months",
    level: "A1",
    icon: "📅",
    blurb: "Dutch writes these lowercase — no capitals, unlike English.",
    items: [
      { target: "maandag", en: "Monday" },
      { target: "dinsdag", en: "Tuesday" },
      { target: "woensdag", en: "Wednesday" },
      { target: "donderdag", en: "Thursday" },
      { target: "vrijdag", en: "Friday" },
      { target: "zaterdag", en: "Saturday" },
      { target: "zondag", en: "Sunday" },
      { target: "vandaag", en: "today" },
      { target: "gisteren", en: "yesterday" },
      { target: "morgen", en: "tomorrow" },
      { target: "week", article: "de", plural: "weken", en: "week" },
      { target: "maand", article: "de", plural: "maanden", en: "month" },
      { target: "jaar", article: "het", plural: "jaren", en: "year" },
    ],
    examples: [
      { target: "Vandaag is het maandag.", en: "Today is Monday." },
      { target: "Tot vrijdag!", en: "See you Friday!" },
    ],
  },
  {
    id: "huis-woorden",
    title: "In huis",
    titleEn: "Around the house",
    level: "A1",
    icon: "🏠",
    blurb: "Rooms and furniture — and a good place to notice how Dutch glues words together.",
    items: [
      { target: "huis", article: "het", plural: "huizen", en: "house", icon: "🏠" },
      { target: "kamer", article: "de", plural: "kamers", en: "room" },
      { target: "keuken", article: "de", plural: "keukens", en: "kitchen" },
      { target: "badkamer", article: "de", plural: "badkamers", en: "bathroom" },
      { target: "slaapkamer", article: "de", plural: "slaapkamers", en: "bedroom" },
      { target: "woonkamer", article: "de", plural: "woonkamers", en: "living room" },
      { target: "tuin", article: "de", plural: "tuinen", en: "garden" },
      { target: "deur", article: "de", plural: "deuren", en: "door", icon: "🚪" },
      { target: "raam", article: "het", plural: "ramen", en: "window", icon: "🪟" },
      { target: "tafel", article: "de", plural: "tafels", en: "table" },
      { target: "stoel", article: "de", plural: "stoelen", en: "chair", icon: "🪑" },
      { target: "bed", article: "het", plural: "bedden", en: "bed", icon: "🛏️" },
    ],
    examples: [
      { target: "De keuken is klein.", en: "The kitchen is small." },
      { target: "Het bed staat in de slaapkamer.", en: "The bed is in the bedroom." },
    ],
  },
  {
    id: "werkwoorden",
    title: "Veelgebruikte werkwoorden",
    titleEn: "Common verbs",
    level: "A1",
    icon: "🏃",
    blurb:
      "The forty verbs that carry most of everyday Dutch. Learn these and the sentence builder does the rest.",
    items: [
      { target: "zijn", en: "to be", say: "zayn" },
      { target: "hebben", en: "to have" },
      { target: "gaan", en: "to go" },
      { target: "komen", en: "to come" },
      { target: "doen", en: "to do" },
      { target: "maken", en: "to make" },
      { target: "zien", en: "to see" },
      { target: "weten", en: "to know (a fact)" },
      { target: "kennen", en: "to know (a person)" },
      { target: "denken", en: "to think" },
      { target: "zeggen", en: "to say" },
      { target: "vragen", en: "to ask" },
      { target: "geven", en: "to give" },
      { target: "nemen", en: "to take" },
      { target: "eten", en: "to eat" },
      { target: "drinken", en: "to drink" },
      { target: "slapen", en: "to sleep" },
      { target: "werken", en: "to work" },
      { target: "wonen", en: "to live / reside" },
      { target: "spelen", en: "to play" },
      { target: "lezen", en: "to read" },
      { target: "schrijven", en: "to write" },
      { target: "praten", en: "to talk" },
      { target: "luisteren", en: "to listen" },
      { target: "kijken", en: "to look / watch" },
      { target: "lopen", en: "to walk" },
      { target: "fietsen", en: "to cycle" },
      { target: "rijden", en: "to drive" },
      { target: "kopen", en: "to buy" },
      { target: "betalen", en: "to pay" },
      { target: "helpen", en: "to help" },
      { target: "leren", en: "to learn / teach" },
      { target: "beginnen", en: "to begin" },
      { target: "stoppen", en: "to stop" },
      { target: "vinden", en: "to find / to think of" },
      { target: "houden", en: "to hold / to keep" },
      { target: "willen", en: "to want" },
      { target: "kunnen", en: "can / to be able" },
      { target: "moeten", en: "must / to have to" },
      { target: "mogen", en: "may / to be allowed" },
    ],
    examples: [
      { target: "Ik drink koffie.", en: "I drink coffee." },
      { target: "Jij werkt hard.", en: "You work hard." },
      { target: "Wij eten brood.", en: "We eat bread." },
    ],
  },
];
